### ISSUE TITLE
可以考虑增加Vercel部署方式吗

### ISSUE THREAD

**Issue by juneix** [huankong233/94list-laravel#10]
我尝试用Vercel部署，貌似是支持的（框架识别出来了）？但是最后报错了。

**Comment by huankong233** [comment]
https://imagdic.me/blog/deploying-laravel-application-to-vercel/

**Comment by juneix** [comment]
> https://imagdic.me/blog/deploying-laravel-application-to-vercel/

感谢大佬，借助搜索引擎和ai工具，小白勉强部署成功了。但是现在初始化安装又出问题了。无论选sqlite还是mysql都提示「服务器错误」

注：mysql我用的db4free，测试过是能正常登录的。

**Comment by huankong233** [comment]
> > https://imagdic.me/blog/deploying-laravel-application-to-vercel/
> 
> 感谢大佬，借助搜索引擎和ai工具，小白勉强部署成功了。但是现在初始化安装又出问题了。无论选sqlite还是mysql都提示「服务器错误」
> 
> 注：mysql我用的db4free，测试过是能正常登录的。

.env里打开debug模式，报错给我看看
