### ISSUE TITLE
批量删除报错

### ISSUE THREAD

**Issue by yzq313** [huankong233/94list-laravel#106]
![image](https://github.com/huankong233/94list-laravel/assets/67686611/a9daf676-c375-4a59-880f-f2a32f0d0743)

**Comment by huankong233** [comment]
> ![image](https://private-user-images.githubusercontent.com/67686611/334784404-a9daf676-c375-4a59-880f-f2a32f0d0743.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY5ODM0MDUsIm5iZiI6MTcxNjk4MzEwNSwicGF0aCI6Ii82NzY4NjYxMS8zMzQ3ODQ0MDQtYTlkYWY2NzYtYzM3NS00YTU5LTg4MGYtZjJhMzJmMGQwNzQzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI5VDExNDUwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNmZTc4ZTdjNTk0ZDhkODAzMDYwMGUwODc3YTNhZWQyODk0ZDAwNDc5NzlkMjIyNGU2OGQwNDAzMDU3YWIzZWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.dZGJOw3od6YJo6STeY1C38y6a4ktJDNId3nguh-Ck8k)

复现步骤

**Comment by yzq313** [comment]
6个以上批量用户删除

**Comment by huankong233** [comment]
> ![image](https://private-user-images.githubusercontent.com/67686611/334784404-a9daf676-c375-4a59-880f-f2a32f0d0743.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcwNDYzNjIsIm5iZiI6MTcxNzA0NjA2MiwicGF0aCI6Ii82NzY4NjYxMS8zMzQ3ODQ0MDQtYTlkYWY2NzYtYzM3NS00YTU5LTg4MGYtZjJhMzJmMGQwNzQzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTMwVDA1MTQyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThkYWFhOGYzNmMxOTQyODA3YTk1YmE3MGYyMTU0NDg0Y2U1ZTRiZjkzZDQxNzRjZGMwMDY0MmY4ZmQ0YjgyNWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.BzLhAMjq0-lLpqVR4vHyUGOFhKFP-CZ7x77p8METSts)

版本号

**Comment by huankong233** [comment]
已知错误，等待下个版本发布
