### ISSUE TITLE
最近风控升级了，解析接口需要更换

### ISSUE THREAD

**Issue by MoTeam-org** [huankong233/94list-laravel#108]
我发现，最近百度的风控再一次升级，Share接口基本都要废了，一旦检测到，返回的Code都是9019，也就是风控了，且似乎无法解开，也就是风控账号连分享链接都打不开，不采用SahreDownload，现在看list都是返回code9019了，你的接口需要调整啦

**Comment by MoTeam-org** [comment]
对了，还有一点，你的逻辑有点问题，当账号处于使用正常状态时，如果会员过期，就会Server Error ，开DeBug就显示未定义svip字段，这个需要解决下

**Comment by huankong233** [comment]
> 对了，还有一点，你的逻辑有点问题，当账号处于使用正常状态时，如果会员过期，就会Server Error ，开DeBug就显示未定义svip字段，这个需要解决下

是哪个版本

**Comment by huankong233** [comment]
> 我发现，最近百度的风控再一次升级，Share接口基本都要废了，一旦检测到，返回的Code都是9019，也就是风控了，且似乎无法解开，也就是风控账号连分享链接都打不开，不采用SahreDownload，现在看list都是返回code9019了，你的接口需要调整啦

这个确实注意到了，有人反馈了

**Comment by MoTeam-org** [comment]
> > 对了，还有一点，你的逻辑有点问题，当账号处于使用正常状态时，如果会员过期，就会Server Error ，开DeBug就显示未定义svip字段，这个需要解决下
> 
> 是哪个版本

这个
![image](https://github.com/huankong233/94list-laravel/assets/112475198/67f8fd12-c496-44e3-85be-d8c34b6fd9bd)

**Comment by huankong233** [comment]
> > > 对了，还有一点，你的逻辑有点问题，当账号处于使用正常状态时，如果会员过期，就会Server Error ，开DeBug就显示未定义svip字段，这个需要解决下
> > 
> > 
> > 是哪个版本
> 
> 这个 ![image](https://private-user-images.githubusercontent.com/112475198/335770509-67f8fd12-c496-44e3-85be-d8c34b6fd9bd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcyMDY3NTMsIm5iZiI6MTcxNzIwNjQ1MywicGF0aCI6Ii8xMTI0NzUxOTgvMzM1NzcwNTA5LTY3ZjhmZDEyLWM0OTYtNDRlMy04NWJlLWQ4YzM0YjZmZDliZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwMVQwMTQ3MzNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05ZGFkYzhjOTE3NjIyYTlmM2NhM2JjMmU2MDYzYmI1OGZhMmI4Y2Q2NGJhNzdhZmQ0YTQ3YWJmZWRhZDVjNjExJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.CSRVOiJ_dlXFeNWLxHAVH3O1y97gh2qU7h2s_fHw-Ok)

那已经很老了，很久之前就已经修了那个问题，解析接口倒是确实要改了

**Comment by MoTeam-org** [comment]
> > > > 对了，还有一点，你的逻辑有点问题，当账号处于使用正常状态时，如果会员过期，就会Server Error ，开DeBug就显示未定义svip字段，这个需要解决下
> > > 
> > > 
> > > 是哪个版本
> > 
> > 
> > 这个 ![image](https://private-user-images.githubusercontent.com/112475198/335770509-67f8fd12-c496-44e3-85be-d8c34b6fd9bd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcyMDY3NTMsIm5iZiI6MTcxNzIwNjQ1MywicGF0aCI6Ii8xMTI0NzUxOTgvMzM1NzcwNTA5LTY3ZjhmZDEyLWM0OTYtNDRlMy04NWJlLWQ4YzM0YjZmZDliZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwMVQwMTQ3MzNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05ZGFkYzhjOTE3NjIyYTlmM2NhM2JjMmU2MDYzYmI1OGZhMmI4Y2Q2NGJhNzdhZmQ0YTQ3YWJmZWRhZDVjNjExJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.CSRVOiJ_dlXFeNWLxHAVH3O1y97gh2qU7h2s_fHw-Ok)
> 
> 那已经很老了，很久之前就已经修了那个问题，解析接口倒是确实要改了

你的最新版用不来...所以就没更新

**Comment by huankong233** [comment]
> > > > > 对了，还有一点，你的逻辑有点问题，当账号处于使用正常状态时，如果会员过期，就会Server Error ，开DeBug就显示未定义svip字段，这个需要解决下
> > > > 
> > > > 
> > > > 是哪个版本
> > > 
> > > 
> > > 这个 ![image](https://private-user-images.githubusercontent.com/112475198/335770509-67f8fd12-c496-44e3-85be-d8c34b6fd9bd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcyMDY3NTMsIm5iZiI6MTcxNzIwNjQ1MywicGF0aCI6Ii8xMTI0NzUxOTgvMzM1NzcwNTA5LTY3ZjhmZDEyLWM0OTYtNDRlMy04NWJlLWQ4YzM0YjZmZDliZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwMVQwMTQ3MzNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05ZGFkYzhjOTE3NjIyYTlmM2NhM2JjMmU2MDYzYmI1OGZhMmI4Y2Q2NGJhNzdhZmQ0YTQ3YWJmZWRhZDVjNjExJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.CSRVOiJ_dlXFeNWLxHAVH3O1y97gh2qU7h2s_fHw-Ok)
> > 
> > 
> > 那已经很老了，很久之前就已经修了那个问题，解析接口倒是确实要改了
> 
> 你的最新版用不来...所以就没更新

用不了就检查php版本，新的升级到laravel11，php强制要求 >= 8.1 了

**Comment by GUGUJI6666** [comment]
用不了就检查php版本，新的升级到laravel11，php强制要求 >= 8.1 了

你好，请问宝塔可以使用这个laravel 11吗 之前安装是使用laravel 5这个伪静态

**Comment by GUGUJI6666** [comment]
> > > > > > 对了，还有一点，你的逻辑有点问题，当账号处于使用正常状态时，如果会员过期，就会Server Error ，开DeBug就显示未定义svip字段，这个需要解决下
> > > > > 
> > > > > 
> > > > > 是哪个版本
> > > > 
> > > > 
> > > > 这个![图像](https://private-user-images.githubusercontent.com/112475198/335770509-67f8fd12-c496-44e3-85be-d8c34b6fd9bd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcyMDY3NTMsIm5iZiI6MTcxNzIwNjQ1MywicGF0aCI6Ii8xMTI0NzUxOTgvMzM1NzcwNTA5LTY3ZjhmZDEyLWM0OTYtNDRlMy04NWJlLWQ4YzM0YjZmZDliZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwMVQwMTQ3MzNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05ZGFkYzhjOTE3NjIyYTlmM2NhM2JjMmU2MDYzYmI1OGZhMmI4Y2Q2NGJhNzdhZmQ0YTQ3YWJmZWRhZDVjNjExJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.CSRVOiJ_dlXFeNWLxHAVH3O1y97gh2qU7h2s_fHw-Ok)
> > > 
> > > 
> > > 那已经很老了，很久之前就已经修了那个问题，解析接口倒是确实要改了
> > 
> > 
> > 你的最新版用不来...所以就没更新
> 
> 用不了就检查php版本，新的升级到laravel11，php强制要求 >= 8.1 了

你好，请问宝塔可以使用这个laravel 11吗 之前安装是使用laravel 5这个伪静态

**Comment by huankong233** [comment]
> > > > > > > 对了，还有一点，你的逻辑有点问题，当账号处于使用正常状态时，如果会员过期，就会Server Error ，开DeBug就显示未定义svip字段，这个需要解决下
> > > > > > 
> > > > > > 
> > > > > > 是哪个版本
> > > > > 
> > > > > 
> > > > > 这个![图像](https://private-user-images.githubusercontent.com/112475198/335770509-67f8fd12-c496-44e3-85be-d8c34b6fd9bd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcyMDY3NTMsIm5iZiI6MTcxNzIwNjQ1MywicGF0aCI6Ii8xMTI0NzUxOTgvMzM1NzcwNTA5LTY3ZjhmZDEyLWM0OTYtNDRlMy04NWJlLWQ4YzM0YjZmZDliZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwMVQwMTQ3MzNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05ZGFkYzhjOTE3NjIyYTlmM2NhM2JjMmU2MDYzYmI1OGZhMmI4Y2Q2NGJhNzdhZmQ0YTQ3YWJmZWRhZDVjNjExJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.CSRVOiJ_dlXFeNWLxHAVH3O1y97gh2qU7h2s_fHw-Ok)
> > > > 
> > > > 
> > > > 那已经很老了，很久之前就已经修了那个问题，解析接口倒是确实要改了
> > > 
> > > 
> > > 你的最新版用不来...所以就没更新
> > 
> > 
> > 用不了就检查php版本，新的升级到laravel11，php强制要求 >= 8.1 了
> 
> 你好，请问宝塔可以使用这个laravel 11吗 之前安装是使用laravel 5这个伪静态

伪静态没关系

**Comment by GUGUJI6666** [comment]
> > > > > > > > 对了，还有一点，你的逻辑有点问题，当账号处于使用正常状态时，如果会员过期，就会Server Error ，开DeBug就显示未定义svip字段，这个需要解决下
> > > > > > > 
> > > > > > > 
> > > > > > > 是哪个版本
> > > > > > 
> > > > > > 
> > > > > > 这个![图像](https://private-user-images.githubusercontent.com/112475198/335770509-67f8fd12-c496-44e3-85be-d8c34b6fd9bd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcyMDY3NTMsIm5iZiI6MTcxNzIwNjQ1MywicGF0aCI6Ii8xMTI0NzUxOTgvMzM1NzcwNTA5LTY3ZjhmZDEyLWM0OTYtNDRlMy04NWJlLWQ4YzM0YjZmZDliZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwMVQwMTQ3MzNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05ZGFkYzhjOTE3NjIyYTlmM2NhM2JjMmU2MDYzYmI1OGZhMmI4Y2Q2NGJhNzdhZmQ0YTQ3YWJmZWRhZDVjNjExJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.CSRVOiJ_dlXFeNWLxHAVH3O1y97gh2qU7h2s_fHw-Ok)
> > > > > 
> > > > > 
> > > > > 那已经很老了，很久之前就已经修了那个问题，解析接口倒是确实要改了
> > > > 
> > > > 
> > > > 你的最新版用不来...所以就没更新
> > > 
> > > 
> > > 用不了就检查php版本，新的升级到laravel11，php强制要求 >= 8.1 了
> > 
> > 
> > 你好，请问宝塔可以使用这个laravel 11吗 之前安装是使用laravel 5这个伪静态
> 
> 伪静态没关系，正确配置访问目录即可

![Uploading 微信图片_20240604184855.jpg…]()

**Comment by GUGUJI6666** [comment]
![微信图片_20240604184855](https://github.com/huankong233/94list-laravel/assets/171681628/454b25da-f403-48d1-ba49-e2dec053d876)
显示这个

**Comment by GUGUJI6666** [comment]
伪静态还是larave5

**Comment by huankong233** [comment]
> ![微信图片_20240604184855](https://private-user-images.githubusercontent.com/171681628/336419241-454b25da-f403-48d1-ba49-e2dec053d876.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc0OTg1ODEsIm5iZiI6MTcxNzQ5ODI4MSwicGF0aCI6Ii8xNzE2ODE2MjgvMzM2NDE5MjQxLTQ1NGIyNWRhLWY0MDMtNDhkMS1iYTQ5LWUyZGVjMDUzZDg3Ni5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwNFQxMDUxMjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02ZDc1ZTE2ZTIzZjYzOTA2MGU1ZGUyMDFiZDVlZDgzOTVmYmRhMWVjOWExNDlkZjJiOWI2MDA5ZDZjMDYwOGQzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.yMmZ_O4ARXYHyjP19667WBPJKCwCcc7F1PxmcWINV18) 显示这个

看[安装教程](https://github.com/huankong233/94list-laravel?tab=readme-ov-file#%E6%99%AE%E9%80%9A%E5%AE%89%E8%A3%85)

**Comment by GUGUJI6666** [comment]
> > ![微信图片_20240604184855](https://private-user-images.githubusercontent.com/171681628/336419241-454b25da-f403-48d1-ba49-e2dec053d876.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc0OTg1ODEsIm5iZiI6MTcxNzQ5ODI4MSwicGF0aCI6Ii8xNzE2ODE2MjgvMzM2NDE5MjQxLTQ1NGIyNWRhLWY0MDMtNDhkMS1iYTQ5LWUyZGVjMDUzZDg3Ni5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwNFQxMDUxMjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02ZDc1ZTE2ZTIzZjYzOTA2MGU1ZGUyMDFiZDVlZDgzOTVmYmRhMWVjOWExNDlkZjJiOWI2MDA5ZDZjMDYwOGQzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.yMmZ_O4ARXYHyjP19667WBPJKCwCcc7F1PxmcWINV18) 显示这个
> 
> 看[安装教程](https://github.com/huankong233/94list-laravel?tab=readme-ov-file#%E6%99%AE%E9%80%9A%E5%AE%89%E8%A3%85)

作者你这个最新版本是改了新的解析接口吗？听说现在解析接口官方都禁止了.....

**Comment by MoTeam-org** [comment]
> > 我发现，最近百度的风控再一次升级，Share接口基本都要废了，一旦检测到，返回的Code都是9019，也就是风控了，且似乎无法解开，也就是风控账号连分享链接都打不开，不采用SahreDownload，现在看list都是返回code9019了，你的接口需要调整啦
> 
> 这个确实注意到了，有人反馈了

当前已经明确，百度已经禁止大文件走Share接口了，无论是否验证码正常，且小文件还是正常的，反正是最近太多xxs搭建Pandownload网页版导致百度修改接口，现在Share接口基本死透了

**Comment by GUGUJI6666** [comment]
> > > 我发现，最近百度的风控再一次升级，Share接口基本都要废了，一旦检测到，返回的Code都是9019，也就是风控了，且似乎无法解开，也就是风控账号连分享链接都打不开，不采用SahreDownload，现在看list都是返回code9019了，你的接口需要调整啦
> > 
> > 
> > 这个确实注意到了，有人反馈了
> 
> 当前已经明确，百度已经禁止大文件走Share接口了，无论是否验证码正常，且小文件还是正常的，反正是最近太多xxs搭建Pandownload网页版导致百度修改接口，现在Share接口基本死透了

yuantuo那个网页版吗哈哈
