### ISSUE TITLE
请问该如何直接请求某一个具体的API信息

### ISSUE THREAD

**Issue by Markli66** [huankong233/94list-laravel#11]
是这样的，我在通过Postman或者CURL直接去请求某一个链接的时候是需要x-xsrf-token这样的参数，类似java中的jwt似的。挺好奇如果我直接在浏览器完成获取fasi_id singn等操作之后是不是就直接可以通过downloadFiles这个api接口去请求直链下载呢？

**Comment by huankong233** [comment]
> 是这样的，我在通过Postman或者CURL直接去请求某一个链接的时候是需要x-xsrf-token这样的参数，类似java中的jwt似的。挺好奇如果我直接在浏览器完成获取fasi_id singn等操作之后是不是就直接可以通过downloadFiles这个api接口去请求直链下载呢？

可以直接用python的 request.session

**Comment by huankong233** [comment]
> 是这样的，我在通过Postman或者CURL直接去请求某一个链接的时候是需要x-xsrf-token这样的参数，类似java中的jwt似的。挺好奇如果我直接在浏览器完成获取fasi_id singn等操作之后是不是就直接可以通过downloadFiles这个api接口去请求直链下载呢？

后面我会用一个更好的方法来解决这个问题 ）
现在在把前后端分离，在重写前端

**Comment by huankong233** [comment]
> 是这样的，我在通过Postman或者CURL直接去请求某一个链接的时候是需要x-xsrf-token这样的参数，类似java中的jwt似的。挺好奇如果我直接在浏览器完成获取fasi_id singn等操作之后是不是就直接可以通过downloadFiles这个api接口去请求直链下载呢？

现在请求已经不需要了，但是后台登陆部分需要
