### ISSUE TITLE
无法解析

### ISSUE THREAD

**Issue by xp9477** [huankong233/94list-laravel#111]
![image](https://github.com/huankong233/94list-laravel/assets/36835224/9fa66e5c-c87b-4cc1-811b-4abe9aa6068e)

**Comment by huankong233** [comment]
https://github.com/yuantuo666/baiduwp-php/blob/73106353dfe221494c50a28b96ebba364c74e94c/app/Parse.php#L379

我尝试过手动传入验证码字段，但是无效，多试几次就又可以解析
