### ISSUE TITLE
代理账号失效或者IP被封禁提示问题

### ISSUE THREAD

**Issue by lingyunytc** [huankong233/94list-laravel#13]
在账号完全可用（已测试两个账号均可正常下载），IP已更改的情况下，解析仍然提示代理账号失效或者IP被封禁

**Comment by lingyunytc** [comment]
![image](https://github.com/huankong233/94list-laravel/assets/61460076/d21cd1d0-4a92-4c96-a700-311015102b07)
现在是118

**Comment by huankong233** [comment]
换一个获取列表的cookie试试看

**Comment by lingyunytc** [comment]
> 换一个获取列表的cookie尝试看看

还是不行，这个是不是要精简一下
![image](https://github.com/huankong233/94list-laravel/assets/61460076/18204acd-5d8e-4a61-8a62-8195b175391e)

**Comment by huankong233** [comment]
> > 换一个获取列表的cookie尝试看看
> 
> 还是不行，这个是不是要精简一下 ![image](https://user-images.githubusercontent.com/61460076/275326742-18204acd-5d8e-4a61-8a62-8195b175391e.png)

你这个cookie是有账户登陆了的吗，还是没登陆的，换成这个试试看

`
csrfToken=rK44XIDDKk8WbCMX_EmEFzp3; newlogin=1; BAIDUID=E17D7A9D6FE00C7BB3F3755BA662FF64:FG=1; BAIDUID_BFESS=E17D7A9D6FE00C7BB3F3755BA662FF64:FG=1
`

**Comment by lingyunytc** [comment]
> > > 换一个获取列表的cookie尝试看看
> > 
> > 
> > 还是不行，这个是不是要精简一下 ![image](https://user-images.githubusercontent.com/61460076/275326742-18204acd-5d8e-4a61-8a62-8195b175391e.png)
> 
> 你这个cookie是有账户登陆了的吗，还是没登陆的，换成这个试试看
> 
> `csrfToken=rK44XIDDKk8WbCMX_EmEFzp3; newlogin=1; BAIDUID=E17D7A9D6FE00C7BB3F3755BA662FF64:FG=1; BAIDUID_BFESS=E17D7A9D6FE00C7BB3F3755BA662FF64:FG=1`

一样，客户端下载正常
![image](https://github.com/huankong233/94list-laravel/assets/61460076/6f256f14-2427-4a6e-93db-b7c5dea76902)

**Comment by huankong233** [comment]
> > > > 换一个获取列表的cookie尝试看看
> > > 
> > > 
> > > 还是不行，这个是不是要精简一下 ![image](https://user-images.githubusercontent.com/61460076/275326742-18204acd-5d8e-4a61-8a62-8195b175391e.png)
> > 
> > 
> > 你这个cookie是有账户登陆了的吗，还是没登陆的，换成这个试试看
> > `csrfToken=rK44XIDDKk8WbCMX_EmEFzp3; newlogin=1; BAIDUID=E17D7A9D6FE00C7BB3F3755BA662FF64:FG=1; BAIDUID_BFESS=E17D7A9D6FE00C7BB3F3755BA662FF64:FG=1`
> 
> 一样，客户端下载正常 ![image](https://user-images.githubusercontent.com/61460076/275326873-6f256f14-2427-4a6e-93db-b7c5dea76902.png)

撕，这我真不是很清楚了
![image](https://github.com/huankong233/94list-laravel/assets/49610758/236d9414-0a05-43c6-ae04-7af770a668f9)

**Comment by lingyunytc** [comment]
> > > 换一个获取列表的cookie尝试看看
> > 
> > 
> > 还是不行，这个是不是要精简一下 ![image](https://user-images.githubusercontent.com/61460076/275326742-18204acd-5d8e-4a61-8a62-8195b175391e.png)
> 
> 你这个cookie是有账户登陆了的吗，还是没登陆的，换成这个试试看
> 
> `csrfToken=rK44XIDDKk8WbCMX_EmEFzp3; newlogin=1; BAIDUID=E17D7A9D6FE00C7BB3F3755BA662FF64:FG=1; BAIDUID_BFESS=E17D7A9D6FE00C7BB3F3755BA662FF64:FG=1`

代理账号包含了BDUSS，PANPSC，STOKEN

**Comment by huankong233** [comment]
> > > > 换一个获取列表的cookie尝试看看
> > > 
> > > 
> > > 还是不行，这个是不是要精简一下 ![image](https://user-images.githubusercontent.com/61460076/275326742-18204acd-5d8e-4a61-8a62-8195b175391e.png)
> > 
> > 
> > 你这个cookie是有账户登陆了的吗，还是没登陆的，换成这个试试看
> > `csrfToken=rK44XIDDKk8WbCMX_EmEFzp3; newlogin=1; BAIDUID=E17D7A9D6FE00C7BB3F3755BA662FF64:FG=1; BAIDUID_BFESS=E17D7A9D6FE00C7BB3F3755BA662FF64:FG=1`
> 
> 代理账号包含了BDUSS，PANPSC，STOKEN

方便留个qq吗

**Comment by lingyunytc** [comment]
> > > > > 换一个获取列表的cookie尝试看看
> > > > 
> > > > 
> > > > 还是不行，这个是不是要精简一下 ![image](https://user-images.githubusercontent.com/61460076/275326742-18204acd-5d8e-4a61-8a62-8195b175391e.png)
> > > 
> > > 
> > > 你这个cookie是有账户登陆了的吗，还是没登陆的，换成这个试试看
> > > `csrfToken=rK44XIDDKk8WbCMX_EmEFzp3; newlogin=1; BAIDUID=E17D7A9D6FE00C7BB3F3755BA662FF64:FG=1; BAIDUID_BFESS=E17D7A9D6FE00C7BB3F3755BA662FF64:FG=1`
> > 
> > 
> > 代理账号包含了BDUSS，PANPSC，STOKEN
> 
> 方便留个qq吗

2092816982

**Comment by huankong233** [comment]
已修复
