### ISSUE TITLE
目录映射无法区分文件与文件夹

### ISSUE THREAD

**Issue by Aqr-K** [huankong233/94list-laravel#14]
提个建议，我是docker平台，用portainer进行部署的，部署的时候发现，在映射的时候，主机目录下如果没有.env与install.lock文件，会被自动映射成文件夹而不是文件，而直接映射html文件夹的话也是不行的，整个文件夹都会空了的，
能不能改一下目录结构，将两个文件提取出来，单独放置一个文件夹里，只将这个文件夹映射，可以加个开机sh脚本，做个判定，如果该文件夹下的俩文件不存在或者该文件大小为0时，直接覆盖复制一份到映射目录里

**Comment by huankong233** [comment]
> 提个建议，我是docker平台，用portainer进行部署的，部署的时候发现，在映射的时候，主机目录下如果没有.env与install.lock文件，会被自动映射成文件夹而不是文件，而直接映射html文件夹的话也是不行的，整个文件夹都会空了的， 能不能改一下目录结构，将两个文件提取出来，单独放置一个文件夹里，只将这个文件夹映射，可以加个开机sh脚本，做个判定，如果该文件夹下的俩文件不存在或者该文件大小为0时，直接覆盖复制一份到映射目录里

我也想解决这个问题，但是不是很会，我docker也用的不是很熟悉，可以的话可以提交pr

**Comment by Aqr-K** [comment]
感觉启动文件有问题，我之前查看了一下，前面的pip-nginx里好像是没有安装bash的，所以你的sh脚本不能用`#!/bin/bash`会出错的

**Comment by huankong233** [comment]
> 感觉启动文件有问题，我之前查看了一下，前面的pip-nginx里好像是没有安装bash的，所以你的sh脚本不能用`#!/bin/bash`，否则会出错的

好，我改一下，不知道为什么会报错

提示我文件不存在，奇怪了

~~~Dockerfile
FROM composer AS composer

COPY . /app

RUN composer install --optimize-autoloader --no-interaction --no-progress

FROM huankong233/php-nginx:latest

COPY --chown=nobody nginx.conf /etc/nginx/conf.d/default.conf

# 复制到文件夹内，运行时判断是否复制
COPY --chown=nobody --from=composer /app /var/www/94list-laravel

COPY --chown=nobody entrypoint.sh /var/www/94list-laravel/entrypoint.sh
RUN chmod a+x /var/www/94list-laravel/entrypoint.sh

ENTRYPOINT ["/var/www/94list-laravel/entrypoint.sh"]
# Let supervisord start nginx & php-fpm
CMD ["/usr/bin/supervisord", "-c", "/etc/supervisor/conf.d/supervisord.conf"]
~~~

**Comment by huankong233** [comment]
起来了！看来那个文件不存在的问题就是 用成 bash 了，谢谢提醒

**Comment by Aqr-K** [comment]
可以加一下这串，默认设置一下开放的端口和需要映射的目录
```
EXPOSE 8080

VOLUME ["/var/www/html"]
```

**Comment by huankong233** [comment]
> 可以加一下这串，默认设置一下开放的端口和需要映射的目录
> 
> ```
> EXPOSE 8080
> 
> VOLUME ["/var/www/html"]
> ```

EXPOSE 在上面的设置了

https://github.com/TrafeX/docker-php-nginx/blob/master/Dockerfile#L58

**Comment by huankong233** [comment]
我后面如果需要用sh复制

cp: can't create '/var/www/html/CHANGELOG.md': Permission denied
cp: can't create '/var/www/html/Dockerfile': Permission denied
cp: can't create '/var/www/html/README.md': Permission denied
cp: can't create directory '/var/www/html/app': Permission denied
cp: can't create '/var/www/html/artisan': Permission denied
cp: can't create directory '/var/www/html/bootstrap': Permission denied
cp: can't create '/var/www/html/composer.json': Permission denied
cp: can't create '/var/www/html/composer.lock': Permission denied
cp: can't create directory '/var/www/html/config': Permission denied
cp: can't create directory '/var/www/html/database': Permission denied
cp: can't create '/var/www/html/entrypoint.sh': Permission denied
cp: can't create '/var/www/html/nginx.conf': Permission denied
cp: can't create '/var/www/html/package.json': Permission denied
cp: can't create '/var/www/html/phpunit.xml': Permission denied
cp: can't create directory '/var/www/html/public': Permission denied
cp: can't create directory '/var/www/html/resources': Permission denied
cp: can't create directory '/var/www/html/routes': Permission denied
cp: can't create directory '/var/www/html/storage': Permission denied
cp: can't create directory '/var/www/html/tests': Permission denied
cp: can't create directory '/var/www/html/vendor': Permission denied
cp: can't create '/var/www/html/vite.config.js': Permission denied
cp: can't create '/var/www/html/.env': Permission denied

啊啊啊

**Comment by huankong233** [comment]
> 我后面如果需要用sh复制
> 
> cp: can't create '/var/www/html/CHANGELOG.md': Permission denied cp: can't create '/var/www/html/Dockerfile': Permission denied cp: can't create '/var/www/html/README.md': Permission denied cp: can't create directory '/var/www/html/app': Permission denied cp: can't create '/var/www/html/artisan': Permission denied cp: can't create directory '/var/www/html/bootstrap': Permission denied cp: can't create '/var/www/html/composer.json': Permission denied cp: can't create '/var/www/html/composer.lock': Permission denied cp: can't create directory '/var/www/html/config': Permission denied cp: can't create directory '/var/www/html/database': Permission denied cp: can't create '/var/www/html/entrypoint.sh': Permission denied cp: can't create '/var/www/html/nginx.conf': Permission denied cp: can't create '/var/www/html/package.json': Permission denied cp: can't create '/var/www/html/phpunit.xml': Permission denied cp: can't create directory '/var/www/html/public': Permission denied cp: can't create directory '/var/www/html/resources': Permission denied cp: can't create directory '/var/www/html/routes': Permission denied cp: can't create directory '/var/www/html/storage': Permission denied cp: can't create directory '/var/www/html/tests': Permission denied cp: can't create directory '/var/www/html/vendor': Permission denied cp: can't create '/var/www/html/vite.config.js': Permission denied cp: can't create '/var/www/html/.env': Permission denied
> 
> 啊啊啊

nobody不能复制吗，奇怪了

**Comment by huankong233** [comment]
drwxr-xr-x    2 root     root          4096 Oct 25 10:45 html

?

**Comment by huankong233** [comment]
> drwxr-xr-x 2 root root 4096 Oct 25 10:45 html
> 
> ?

~~~ Dockerfile
FROM composer AS composer

COPY . /app

RUN composer install --optimize-autoloader --no-interaction --no-progress

FROM huankong233/php-nginx:latest

USER root
COPY --chown=nobody nginx.conf /etc/nginx/conf.d/default.conf
COPY --chown=nobody --from=composer /app /var/www/94list-laravel
RUN chown nobody:nogroup /var/www/html
COPY --chown=nobody entrypoint.sh /entrypoint.sh
RUN chmod a+x /entrypoint.sh
USER nobody

VOLUME ["/var/www/html"]
ENTRYPOINT ["/entrypoint.sh"]
# Let supervisord start nginx & php-fpm
CMD ["/usr/bin/supervisord", "-c", "/etc/supervisor/conf.d/supervisord.conf"]
~~~

**Comment by huankong233** [comment]
> > drwxr-xr-x 2 root root 4096 Oct 25 10:45 html
> > ?
> 
> ```dockerfile
> FROM composer AS composer
> 
> COPY . /app
> 
> RUN composer install --optimize-autoloader --no-interaction --no-progress
> 
> FROM huankong233/php-nginx:latest
> 
> USER root
> COPY --chown=nobody nginx.conf /etc/nginx/conf.d/default.conf
> COPY --chown=nobody --from=composer /app /var/www/94list-laravel
> RUN chown nobody:nogroup /var/www/html
> COPY --chown=nobody entrypoint.sh /entrypoint.sh
> RUN chmod a+x /entrypoint.sh
> USER nobody
> 
> VOLUME ["/var/www/html"]
> ENTRYPOINT ["/entrypoint.sh"]
> # Let supervisord start nginx & php-fpm
> CMD ["/usr/bin/supervisord", "-c", "/etc/supervisor/conf.d/supervisord.conf"]
> ```

https://github.com/TrafeX/docker-php-nginx/blob/master/Dockerfile#L46C1-L46C41

我设置成了nobody了啊，为什么没效果

**Comment by Aqr-K** [comment]
我之前试了也是这样，属于html文件夹的问题，它本身是由root用户绑定创建的，你映射的时候相当于root重新赋权了
在dockerfile里设置的权限会在启动还是映射的时候？自己恢复掉了

**Comment by Aqr-K** [comment]
对了，后面我试了一下直接以root启动得了，发现`supervisor`只支持nobody用户，`html`文件夹只要映射就只支持`root`用户写入

**Comment by Aqr-K** [comment]
我知道为什么了，
不是容器的问题，是映射后的权限已经不属于容器本身了，文件夹变成属于宿主机的权限
如果不映射，容器里的html文件还是属于nobody可编辑的，但是现在是映射成了宿主机的文件夹了，使用的权限变成了宿主机的文件夹原本的权限了，需要重新给这个宿主机的文件夹赋权，我在宿主机的文件夹下赋权777，然后就成功启动了
问题来了，项目默认使用的是nobody，所以非root用户无法修改宿主机映射出来的文件夹的权限，目前我想到的解决方法是，将启动时的用户改成root，但是检测并复制完后，通过脚本切换用户，再使用nobody用户启动项目，
这种权限问题是dockerfile是无法解决的

**Comment by huankong233** [comment]
> 对了，后面我试了一下直接以root启动得了，发现`supervisor`只支持nobody用户，`html`文件夹只要映射就只支持`root`用户写入

我再研究一下🤔

**Comment by huankong233** [comment]
~~~ conf
[supervisord]
nodaemon=true
logfile=/dev/null
logfile_maxbytes=0
pidfile=/run/supervisord.pid
user=root

[program:php-fpm]
command=php-fpm82 -F
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
autorestart=false
startretries=0

[program:nginx]
command=nginx -g 'daemon off;'
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
autorestart=false
startretries=0
~~~

设置成root之后 php 启动失败了，nginx能正常启动

**Comment by huankong233** [comment]
> ```
> [supervisord]
> nodaemon=true
> logfile=/dev/null
> logfile_maxbytes=0
> pidfile=/run/supervisord.pid
> user=root
> 
> [program:php-fpm]
> command=php-fpm82 -F
> stdout_logfile=/dev/stdout
> stdout_logfile_maxbytes=0
> stderr_logfile=/dev/stderr
> stderr_logfile_maxbytes=0
> autorestart=false
> startretries=0
> 
> [program:nginx]
> command=nginx -g 'daemon off;'
> stdout_logfile=/dev/stdout
> stdout_logfile_maxbytes=0
> stderr_logfile=/dev/stderr
> stderr_logfile_maxbytes=0
> autorestart=false
> startretries=0
> ```
> 
> 设置成root之后 php 启动失败了，nginx能正常启动

用错版本了，更新一下上游镜像（）

**Comment by Aqr-K** [comment]
给你提供一段命令代码，这是我昨天在root的状态下，手动使用su命令指定nobody用户启动的命令，和你一样，遇到了php启动失败的问题
`su - nobody -s /bin/sh -c "/usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord.conf"`

**Comment by huankong233** [comment]
> 给你提供一段命令代码，这是我昨天在root的状态下，手动使用su命令指定nobody用户启动的命令，和你一样，遇到了php启动失败的问题 `su - nobody -s /bin/ash -c "/usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord.conf"`

可能要改一些配置文件，我还在看

**Comment by huankong233** [comment]
成了，但是都是root权限的了（）

**Comment by huankong233** [comment]
![image](https://github.com/huankong233/94list-laravel/assets/49610758/7a23d3d5-a172-47b5-aa83-7f88cdc9ea30)

**Comment by Aqr-K** [comment]
我随手写了个if判定，但还没测，也可能有写漏或者错的，你可以看看要不要加进去，
本意是打算做个容器变量与.env文件的开关，后面可以写个docker-compose，把需要的变量可以提前注释进去，方便部署使用
需要在dockerfile里加入`ENV_MODE`环境变量，true为使用容器环境，false为使用.env文件
```
if [ "$ENV_MODE" = "true" ]; then 
	echo "当前使用变量模式..."
	cp -f .env .env.bak
	cp -f .env.example .env
	chmod a+x .env
	
elif [ “$env” = “false” ]; then
	echo "当前使用脚本模式..."
	if [ -f .env ]; then
		echo " .env文件已存在 "
	elif [ -f .env.bak ]; then
		echo "检测到配置备份，开始恢复原有配置..."
		cp -f .env.bak .env
		chmod a+x .env
		echo "配置恢复完成..."
else
	echo "ENV_MODE 输入了无效值 $ENV_MODE"
fi
```

**Comment by huankong233** [comment]
> 我随手写了个if判定，但还没测，也可能有写漏或者错的，你可以看看要不要加进去， 本意是打算做个容器变量与.env文件的开关，后面可以写个docker-compose，把需要的变量可以提前注释进去，方便部署使用 需要在dockerfile里加入`ENV_MODE`环境变量，true为使用容器环境，false为使用.env文件
> 
> ```
> ENV_MODE="${ENV_MODE}"
> 
> if [ "$ENV_MODE" = "true" ]; then 
> 	echo "当前使用变量模式..."
> 	cp -f .env .env.bak
> 	cp -f .env.example .env
> 	chmod a+x .env
> 	
> elif [ “$env” = “false” ]; then
> 	echo "当前使用脚本模式..."
> 	if [ -f .env ]; then
> 		echo " .env文件已存在 "
> 	elif [ -f .env.bak ]; then
> 		echo "检测到配置备份，开始恢复原有配置..."
> 		cp -f .env.bak .env
> 		chmod a+x .env
> 		echo "配置恢复完成..."
> 	else
> 	fi
> else
> 	echo "ENV_MODE 输入了无效值 $ENV_MODE"
> fi
> ```

等我把这一小部分搞定，你直接丢pr给我就好 ：）

![image](https://github.com/huankong233/94list-laravel/assets/49610758/814f52e4-7019-4e3d-89ad-35b9f636805b)
搞了个小彩蛋

**Comment by Aqr-K** [comment]
你这个项目的配置有没有调整？我看了一下，没有更新啊？我现在没有你调整后的配置，我想测一下这个if

**Comment by huankong233** [comment]
> 你这个项目的配置有没有调整？我看了一下，没有更新啊？我现在没有你调整后的配置，我想测一下这个if

马上，1分钟

**Comment by huankong233** [comment]
> 你这个项目的配置有没有调整？我看了一下，没有更新啊？我现在没有你调整后的配置，我想测一下这个if
提交了

**Comment by huankong233** [comment]
我突然想起来laravel好像会自动读取系统变量的，在docker-compose那定义应该就可以了

**Comment by Aqr-K** [comment]
我刚刚测了一下，确实可以，不过有个问题，用环境变量绑定的mysql的话，发现它不会自动生成数据库配置了，如果数据库本身就有内容倒是不影响连接， 就是自动化生成配置的问题
一开始以为是install.lock的判定，就随手加了个自动生成install.lock文件，结果还是一样，估计得要加个判定数据库是否为空的命令才行了，这是[目前](https://github.com/Aqr-K/94list-laravel/blob/main/docker/entrypoint.sh)写的

**Comment by huankong233** [comment]
> 我刚刚测了一下，确实可以，不过有个问题，用环境变量绑定的mysql的话，发现它不会自动生成数据库配置了，如果数据库本身就有内容倒是不影响连接， 就是自动化生成配置的问题 一开始以为是install.lock的判定，就随手加了个自动生成install.lock文件，结果还是一样，估计得要加个判定数据库是否为空的命令才行了，这是[目前](https://github.com/Aqr-K/94list-laravel/blob/main/docker/entrypoint.sh)写的

嗯，不会自动生成了，生成的部分写在do_install路由方法里了，自动安装数据库的话，我到时候写在系统里就好，用docker启动的话添加一个环境变量就好了

**Comment by Aqr-K** [comment]
那我暂时就不改了，就先扔着一边了，那个sh里面我加了个app_key的生成，主旨是覆盖默认的key，更安全点
我的那个fork里有写好的[docker-compose](https://github.com/Aqr-K/94list-laravel/blob/main/docker-compose.yml)，你可以套用过去

**Comment by huankong233** [comment]
> 那我暂时就不改了，就先扔着一边了，那个sh里面我加了个app_key的生成，主旨是覆盖默认的key，更安全点 我的那个fork里有写好的[docker-compose](https://github.com/Aqr-K/94list-laravel/blob/main/docker-compose.yml)，你可以套用过去

app_key 的话在安装的时候会生成一次
我加一个中间件就可以解决了 ，我弄一下 ）

**Comment by huankong233** [comment]
> 那我暂时就不改了，就先扔着一边了，那个sh里面我加了个app_key的生成，主旨是覆盖默认的key，更安全点 我的那个fork里有写好的[docker-compose](https://github.com/Aqr-K/94list-laravel/blob/main/docker-compose.yml)，你可以套用过去

现在实现的效果就是在进入任意路由时触发中间件
https://github.com/huankong233/94list-laravel/blob/main/app/Http/Middleware/InstallCheck.php#L32-L64
然后如果没安装就按照现在环境变量里的配置文件然后来自动安装，安装后就会创建好install.lock文件，后期再有修改的话可能就会出一些奇怪的问题，我等下再加个数据库是否有效的判断（¿）应该

**Comment by Aqr-K** [comment]
我修改了一下docker-compose.yml的内容，网页里的可控参数，如公告，调试开关等，不太适合写入docker-compose里，出现了变量高于手动的情况，会导致设置无效化

**Comment by huankong233** [comment]
> 变量

我在后台加个提醒，laravel优先环境变量的
