### ISSUE TITLE
使用docker-compose部署后无法打开页面

### ISSUE THREAD

**Issue by f85386056** [huankong233/94list-laravel#16]
2023-10-30 09:02:14,523 INFO supervisord started with pid 1
2023-10-30 09:02:15,525 INFO spawned: 'nginx' with pid 7
2023-10-30 09:02:15,527 INFO spawned: 'php-fpm' with pid 8
[30-Oct-2023 09:02:15] NOTICE: fpm is running, pid 8
[30-Oct-2023 09:02:15] NOTICE: ready to handle connections
2023-10-30 09:02:16,556 INFO success: nginx entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2023-10-30 09:02:16,557 INFO success: php-fpm entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)

docker 日志打印，同时数据库里没有创建数据

**Comment by f85386056** [comment]
version: '3.8'

services:
  94list-laravel:
    container_name: 94list-laravel
    # 镜像名字
    image: huankong233/94list-laravel:latest
    # 网络模式
    # "bridge"为网桥模式,"host"为主机模式
    network_mode: 'bridge'
    #开放端口
    ports:
      # 左边为外部开放端口，右边为容器内端口，请勿修改右边端口
      - '8080:8080'
    # 目录映射
    volumes:
      # 左侧为宿主机目录，请自行修改，右侧为容器内部目录，请勿修改
      - /home/94list/html:/var/www/html
    # 重启策略
    restart: always
    # 环境变量
    environment:
      ### 模式选择
      #  0 为.env模式
      #  1 为容器环境变量模式 
      # 使用模式0时，必须#注释或删除掉"数据库配置"大项，否则会出现参数被环境变量代替的情况
      # 使用模式1时，可搭配下方数据库配置一同使用
      - APP_INSTALL_MODE=1

      ### 基础配置
      # 网站名字
      - APP_NAME=94list-laravel
      # 网站地址
      - APP_URL=http://此处为服务器ip

      ### 数据库配置
      # db_type有效参数，"sqlite"、"mysql"
      # 如果需要使用sqlite请手动创建好一个空文件，然后在DB_DATABASE中指定数据库文件的绝对位置
      - DB_CONNECTION=mysql
      # 数据库地址
      - DB_HOST=127.0.0.1
      # 数据库端口
      - DB_PORT=3306
      # 数据库名字
      - DB_DATABASE=xxxxxx
      # 用户名
      - DB_USERNAME=xxxxx
      # 登陆密码
      - DB_PASSWORD=xxxxxxxx

      ### 邮箱配置
      # 邮件服务器协议类型
      - MAIL_MAILER=smtp
      # 邮件服务器地址
      - MAIL_HOST=smtp.qq.com
      # 邮件服务器端口
      - MAIL_PORT=465
      # 邮件服务器登陆账号
      - MAIL_USERNAME=hello@example.com
      # 邮件服务器授权码（注意！非账号登陆密码）
      - MAIL_PASSWORD=passwd
      # 邮件服务器加密类型
      - MAIL_ENCRYPTION=TLS
      # 发送人名字
      - MAIL_FROM_ADDRESS=hello@example.com
      # 自定义用户名
      - MAIL_FROM_NAME=自定义用户名

**Comment by f85386056** [comment]
mysql版本为5.7

**Comment by huankong233** [comment]
> mysql版本为5.7

那有被重定向到 `/install` 吗

**Comment by f85386056** [comment]
没有，直接访问ip:8080,没有重定向

**Comment by f85386056** [comment]
奇怪的是html 文件夹下也没有任何东西被创建

**Comment by Aqr-K** [comment]
重新拉一下镜像

**Comment by huankong233** [comment]
> 没有，直接访问ip:8080,没有重定向

打开 app_debug 看看

~~~
- APP_DEBUG=true
~~~

**Comment by huankong233** [comment]
> 重新拉一下镜像

确实有可能不是最新的😂

**Comment by huankong233** [comment]
没有权限应该会报错的）

**Comment by Aqr-K** [comment]
> 奇怪的是html 文件夹下也没有任何东西被创建

大概率是拉到旧版本了，那个没有检测的版本

**Comment by huankong233** [comment]
> > 奇怪的是html 文件夹下也没有任何东西被创建
> 
> 大概率是拉到旧版本了，那个没有检测的版本

可以了吗（）

**Comment by f85386056** [comment]
![image](https://github.com/huankong233/94list-laravel/assets/61175596/adcffd20-7afa-46e3-8470-c4116fdf7082)

**Comment by f85386056** [comment]
镜像版本是这个，应该是最新的吧，现在还是不行，打开了debug也没看到更多的日志

**Comment by huankong233** [comment]
> ![image](https://user-images.githubusercontent.com/61175596/279100771-adcffd20-7afa-46e3-8470-c4116fdf7082.png)

TAG
latest
Last pushed 3 days ago by huankong233
DIGEST
OS/ARCH
COMPRESSED SIZE 
2a89e5f34ef0
linux/amd64

**Comment by Aqr-K** [comment]
如果镜像拉取一直有问题的话，就手动指定版本吧
`docker pull huankong233/94list-laravel:0.1.3`
把docker-compose里的`huankong233/94list-laravel:latest`改成`huankong233/94list-laravel:0.1.3`

**Comment by Aqr-K** [comment]
如果你是国内访问拉取docker镜像太慢了，可以用`docker.nju.edu.cn`镜像站加速
手动`pull`命令改成这个就行
docker pull docker.nju.edu.cn/huankong233/94list-laravel:0.1.3

**Comment by huankong233** [comment]
用portainer什么的可以直接设置镜像的

**Comment by f85386056** [comment]
![image](https://github.com/huankong233/94list-laravel/assets/61175596/5264cd67-ce2a-485e-8d93-ace21223f6e9)
现在是最新版本了，html 文件夹里也有东西了，但是页面还是无法访问

**Comment by Aqr-K** [comment]
日志报错发一下

**Comment by f85386056** [comment]
![image](https://github.com/huankong233/94list-laravel/assets/61175596/80df1e2a-c16c-40fb-8798-0c54d8cf5c0d)

**Comment by f85386056** [comment]
数据库里还是没有新建

**Comment by Aqr-K** [comment]
mysql你要提前创建一个空白数据库，手动创建没

**Comment by f85386056** [comment]
新建了

**Comment by f85386056** [comment]
![image](https://github.com/huankong233/94list-laravel/assets/61175596/ce84ab3d-b585-415e-8085-7a4fbf2525a1)

**Comment by huankong233** [comment]
嗯，库要自己建好，现在在写密码部分，顺便重构了前端优化一下加载速度，不过有别的事搁置了

**Comment by huankong233** [comment]
> ![image](https://user-images.githubusercontent.com/61175596/279103191-80df1e2a-c16c-40fb-8798-0c54d8cf5c0d.png)

有被重定向吗 或者看看根目录下面有 install.lock 文件吗

**Comment by f85386056** [comment]
都没有

**Comment by huankong233** [comment]
> 都没有

🤔，报错有吗

打开页面啥也没有？

**Comment by f85386056** [comment]
就提示响应时间过长...

**Comment by huankong233** [comment]
> 就提示响应时间过长...

😨蛤？

**Comment by huankong233** [comment]
> 就提示响应时间过长...

看看是不是防火墙

如果访问:8080之后docker日志里没有东西出来

**Comment by Aqr-K** [comment]
8080端口能登陆不，不能的话，防火墙放行一下，就算没有数据库，日志也应该会有个报错的访问记录更新的

**Comment by f85386056** [comment]
![image](https://github.com/huankong233/94list-laravel/assets/61175596/1d65cf30-4388-494e-9a15-3271a414f275)

**Comment by f85386056** [comment]
防火墙是关闭状态

**Comment by Aqr-K** [comment]
> 防火墙是关闭状态

我说的服务器宿主机的防火墙

**Comment by f85386056** [comment]
腾讯云
![image](https://github.com/huankong233/94list-laravel/assets/61175596/a3d7224b-2903-428f-9e4c-fffd49c29d75)
![image](https://github.com/huankong233/94list-laravel/assets/61175596/f2a422ca-eaf5-4022-8f91-bbd9cb0ff48c)

**Comment by huankong233** [comment]
> 腾讯云 ![image](https://user-images.githubusercontent.com/61175596/279108317-a3d7224b-2903-428f-9e4c-fffd49c29d75.png) ![image](https://user-images.githubusercontent.com/61175596/279108366-f2a422ca-eaf5-4022-8f91-bbd9cb0ff48c.png)

🤔奇怪了，应该就是没访问到容器
进到容器里top看看呢，nginx和php应该都起来了的

**Comment by huankong233** [comment]
> 腾讯云 ![image](https://user-images.githubusercontent.com/61175596/279108317-a3d7224b-2903-428f-9e4c-fffd49c29d75.png) ![image](https://user-images.githubusercontent.com/61175596/279108366-f2a422ca-eaf5-4022-8f91-bbd9cb0ff48c.png)

是不是规则没用到服务器上¿

重启服务器试试看（）

**Comment by Aqr-K** [comment]
> > 腾讯云 ![image](https://user-images.githubusercontent.com/61175596/279108317-a3d7224b-2903-428f-9e4c-fffd49c29d75.png) ![image](https://user-images.githubusercontent.com/61175596/279108366-f2a422ca-eaf5-4022-8f91-bbd9cb0ff48c.png)
> 
> 是不是规则没用到服务器上¿
> 
> 重启服务器试试看（）

他现在是数据库没有创建数据
我觉得是容器之间的相互访问，不知道被什么莫名其妙的情况隔断了
你的mysql是不是也是docker-compose搭建的，如果是的话，你可以试试将两个docker-compose直接合并成一个创建，同个docker-compose下创建的容器之间，可以直接互相访问，`DB_HOST=你的mysql容器名字`，试试这个方法能不能解决

**Comment by huankong233** [comment]
> > > 腾讯云 ![image](https://user-images.githubusercontent.com/61175596/279108317-a3d7224b-2903-428f-9e4c-fffd49c29d75.png) ![image](https://user-images.githubusercontent.com/61175596/279108366-f2a422ca-eaf5-4022-8f91-bbd9cb0ff48c.png)
> > 
> > 
> > 是不是规则没用到服务器上¿
> > 重启服务器试试看（）
> 
> 他现在是数据库没有创建数据 我觉得是容器之间的相互访问，不知道被什么莫名其妙的情况隔断了 你的mysql是不是也是docker-compose搭建的，如果是的话，你可以试试将两个docker-compose直接合并成一个创建，同个docker-compose下创建的容器之间，可以直接互相访问，`DB_HOST=你的mysql容器名字`，试试这个方法能不能解决

应该不是不能访问mysql的问题，如果不能访问到应该会一段json返回的，自动安装的触发是通过中间件的，需要被访问了才能安装

**Comment by f85386056** [comment]
可以使用了，重启了一下服务可以访问了，但是有个小小的建议，就是docker容器中访问本机的数据库，不能采用127.0.0.1 或者localhost的方式
