### ISSUE TITLE
如果版本更新无法正确替换文件

### ISSUE THREAD

**Issue by huankong233** [huankong233/94list-laravel#19]
如果已经安装好了，然后需要更新，更新完了之后不会对文件进行操作，可能需要对版本号进行判断然后复制指定的文件进去 🤔

现在的判断只是简单判断了文件夹是否为空

https://github.com/huankong233/94list-laravel/blob/main/docker/entrypoint.sh#L6

@Aqr-K

**Comment by Aqr-K** [comment]
写了个2个pr，不是自动化识别版本更新的话，也就是sh里面加个版本号判定的事

**Comment by Aqr-K** [comment]
一个以高版本为主优先使用高版本，一个以内置的94list-laravel的版本为主，两种不同的方式，你选一个吧，或者后面再加个变量选择模式？我感觉好像没啥必要
