### ISSUE TITLE
搭建完毕后访问主页缺少文件

### ISSUE THREAD

**Issue by haobad** [huankong233/94list-laravel#3]
Warning: require(/www/wwwroot/0.0.0.0/public/../vendor/autoload.php): failed to open stream: No such file or directory in /www/wwwroot/0.0.0.0/public/index.php on line 34

Fatal error: require(): Failed opening required '/www/wwwroot/0.0.0.0/public/../vendor/autoload.php' (include_path='.:') in /www/wwwroot/0.0.0.0/public/index.php on line 34

**Comment by huankong233** [comment]
请按照独角数卡那个教程安装laravel的依赖，或者用我打包的docker镜像

**Comment by huankong233** [comment]
> 请按照独角数卡那个教程安装laravel的依赖，或者用我打包的docker镜像

docker镜像的话我晚点公开

**Comment by huankong233** [comment]
[docker地址](https://hub.docker.com/r/huankong233/94list-laravel)

安装只需要一个mysql服务器然后映射两个文件即可
