### ISSUE TITLE
功能提议：代理账号自动刷新

### ISSUE THREAD

**Issue by Aqr-K** [huankong233/94list-laravel#34]
代理账号能不能加一个自动更新的功能，在账号到期后会自动更新信息几次，可以加个类似这样的
![image](https://github.com/huankong233/94list-laravel/assets/95741669/660307b1-e950-4f60-9779-a56dbde30627)
之前我扔了2个号进去，有一个是11月16号到期的，但是号在到期后，是马上续费了的，所以续费后在17号发现，后台不会自动重新刷新cookie的到期时间，得手动更新一下信息才行，
不过不知道在不更新信息的情况下，直接解析会不会成功，会不会刷新到期信息
目前代理账号的管理有批量启动和删除功能，可以考虑再加一个手动的批量更新信息的按钮

**Comment by huankong233** [comment]
> 代理账号能不能加一个自动更新的功能，在账号到期后会自动更新信息几次，可以加个类似这样的 ![image](https://user-images.githubusercontent.com/95741669/284052605-660307b1-e950-4f60-9779-a56dbde30627.png) 之前我扔了2个号进去，有一个是11月16号到期的，但是号在到期后，是马上续费了的，所以续费后在17号发现，后台不会自动重新刷新cookie的到期时间，得手动更新一下信息才行， 不过不知道在不更新信息的情况下，直接解析会不会成功，会不会刷新到期信息 目前代理账号的管理有批量启动和删除功能，可以考虑再加一个手动的批量更新信息的按钮

1.批量更新我晚点加一下
2.自动更新的话，可以考虑在到期的时候重新请求一次确定账户是否到期
3.直接解析应该是可以成功的，但是因为后台判断的时间已经到期，应该请求解析的时候被程序自动禁用

**Comment by Aqr-K** [comment]
或者增加个我图片那种的多选择模式的更新方式也行，cookie没过期且不删的情况下，指不定哪天活了呢？

**Comment by huankong233** [comment]
> 或者增加个我图片那种的多选择模式的更新方式也行，cookie没过期且不删的情况下，指不定哪天活了呢？

定期扫描我觉得不可取，容易黑ip或者账号

**Comment by Aqr-K** [comment]
+

> > 或者增加个我图片那种的多选择模式的更新方式也行，cookie没过期且不删的情况下，指不定哪天活了呢？
> 
> 定期扫描我觉得不可取，容易黑ip或者账号
活号应该怕，但是过期号应该不怕吧？只针对到期的账号呢？

**Comment by huankong233** [comment]
> 活号可能怕，但是过期号应该不怕吧？只针对到期的账号呢？

嗯，所以我说在检测到过期的时候检查一下账户激活状态就好

**Comment by Aqr-K** [comment]
> > 活号可能怕，但是过期号应该不怕吧？只针对到期的账号呢？
> 
> 嗯，所以我说在检测到过期的时候检查一下账户激活状态就好

感觉我的意思没有到位，
我想表达出的效果是当系统检测到过期的`cookie`时，先自动尝试更新信息，并增加一个时候支持手动设置的定时更新，用来更新这一类已经过期的`cookie`，指不定哪天活了呢？
因为如果该账号不是立刻续费了，那么这个检测到过期`cookie`，重新检查账户激活状态的过程，除非是内置了每隔多久检测一次，不然就有可能会出问题了

**Comment by huankong233** [comment]
> > > 活号可能怕，但是过期号应该不怕吧？只针对到期的账号呢？
> > 
> > 
> > 嗯，所以我说在检测到过期的时候检查一下账户激活状态就好
> 
> 感觉我的意思没有到位， 我想表达出的效果是当系统检测到过期的`cookie`时，先自动尝试更新信息，并增加一个时候支持手动设置的定时更新，用来更新这一类已经过期的`cookie`，指不定哪天活了呢？ 因为如果该账号不是立刻续费了，那么这个检测到过期`cookie`，重新检查账户激活状态的过程，除非是内置了每隔多久检测一次，不然就有可能会出问题了

懂了😎

**Comment by huankong233** [comment]
手动批量重新检查账户激活状态已经完成，在账户状态过期时也会自动重新检查(userController::getRandomCookie)

每隔多久检测一次就需要 `supervisor`
