### ISSUE TITLE
想问下，希望看到可以回复~

### ISSUE THREAD

**Issue by MoTeam-org** [huankong233/94list-laravel#39]
这个项目默认调用的是百度网盘官方接口，那么生成的下载链接是nd6.baidupcs.com等接口，但由于大部分解析站基本都是用的这些接口，导致默认接口下载速度无法跑满带宽，而我看到部分解析站的不是这些热门接口，所以我想问下作者大大你知道如何修改请求的百度网盘接口来达到使用这些用的人少的下载接口吗？

**Comment by huankong233** [comment]
> 这个项目默认调用的是百度网盘官方接口，那么生成的下载链接是nd6.baidupcs.com等接口，但由于大部分解析站基本都是用的这些接口，导致默认接口下载速度无法跑满带宽，而我看到部分解析站的不是这些热门接口，所以我想问下作者大大你知道如何修改请求的百度网盘接口来达到使用这些用的人少的下载接口吗？

https://github.com/huankong233/94list-laravel/blob/ed35c415f54addf1376572ab9e4a88a64968e0ad/app/Http/Controllers/UserController.php#L207-L330

**Comment by huankong233** [comment]
> 这个项目默认调用的是百度网盘官方接口，那么生成的下载链接是nd6.baidupcs.com等接口，但由于大部分解析站基本都是用的这些接口，导致默认接口下载速度无法跑满带宽，而我看到部分解析站的不是这些热门接口，所以我想问下作者大大你知道如何修改请求的百度网盘接口来达到使用这些用的人少的下载接口吗？

还有别的接口吗，我这个接口我是在官方PC端找到的解析接口，可能还有别的吧

**Comment by huankong233** [comment]
> > 这个项目默认调用的是百度网盘官方接口，那么生成的下载链接是nd6.baidupcs.com等接口，但由于大部分解析站基本都是用的这些接口，导致默认接口下载速度无法跑满带宽，而我看到部分解析站的不是这些热门接口，所以我想问下作者大大你知道如何修改请求的百度网盘接口来达到使用这些用的人少的下载接口吗？
> 
> 还有别的接口吗，我这个接口我是在官方PC端（百度云管家）找到的解析接口，可能还有别的吧

**Comment by MoTeam-org** [comment]
就是生成的下载链接不是请求接口，我现在想用些参数让生成的链接是用的人少的接口，我想问下怎么弄，我有点蒙圈

**Comment by huankong233** [comment]
> 就是生成的下载链接不是请求接口，我现在想用些参数让生成的链接是用的人少的接口，我想问下怎么弄，我有点蒙圈

生成的地址和请求的地区或者文件存放的数据中心好像都有关系，之前在baiduwp-php issues 里看见过有关问题
