### ISSUE TITLE
需要伪静态吗？(已解决)

### ISSUE THREAD

**Issue by 1Q23LYC45** [huankong233/94list-laravel#4]
看了下独角发卡的安装教程，好像包含了关键词“伪静态”。
请问需要伪静态吗？个人还是有点不喜欢伪静态。
另外docker镜像我用不了，运行必须Root权限，服务器华为手机Kirin710A，Android 10 安全补丁级别2021年12月1日，已经降级到最低系统了，仍然无法解锁BL，也没有提权漏洞，希望出一个Proot/Chroot镜像。谢谢大佬。

**Comment by huankong233** [comment]
> 看了下独角发卡的安装教程，好像包含了关键词“伪静态”。 请问需要伪静态吗？个人还是有点不喜欢伪静态。 另外docker镜像我用不了，运行必须Root权限，服务器华为手机Kirin710A，Android 10 安全补丁级别2021年12月1日，已经降级到最低系统了，仍然无法解锁BL，也没有提权漏洞，希望出一个Proot/Chroot镜像。谢谢大佬。

可以尝试用zerotermux这些来直接跑(可能没有你原来的方案性能更优)，laravel框架是需要伪静态的，因为需要重定向请求到指定的入口文件

**Comment by huankong233** [comment]
> 看了下独角发卡的安装教程，好像包含了关键词“伪静态”。 请问需要伪静态吗？个人还是有点不喜欢伪静态。 另外docker镜像我用不了，运行必须Root权限，服务器华为手机Kirin710A，Android 10 安全补丁级别2021年12月1日，已经降级到最低系统了，仍然无法解锁BL，也没有提权漏洞，希望出一个Proot/Chroot镜像。谢谢大佬。

docker手机上确实不好弄，之前看过，需要自行编译内核什么的，比较麻烦，话说为什么要用手机，也喜欢折腾嘛😂

**Comment by 1Q23LYC45** [comment]
谢谢了，我用的就是Termux。求个Lighttpd用的伪静态配置文件片段。

**Comment by huankong233** [comment]
> 谢谢了，我用的就是Termux。求个Lighttpd用的伪静态配置文件片段。

用Termux的话为什么不用nginx，手机上Lighttpd性能更优嘛🤔

**Comment by huankong233** [comment]
![image](https://github.com/huankong233/94list-laravel/assets/49610758/2e755784-b9d8-4aeb-983b-12b306cbe8cd)

我是搞了一台从小学陪我长大的笔记本来当nas使

**Comment by 1Q23LYC45** [comment]
nginx不太好配置，我喜欢lighttpd，现在手里有一整套Lighttpd配置文件，觉得兼容性和速度都很好。

**Comment by 1Q23LYC45** [comment]
我部署了个nextcloud Nginx直接报错了，Lighttpd非常完美运行。

**Comment by huankong233** [comment]
> nginx不太好配置，我喜欢lighttpd，现在手里有一整套Lighttpd配置文件，觉得兼容性和速度都很好。

不保证一定可以使用，你可以自己看着改一下

~~~
**# Default server definition
server.document-root = "/var/www/html/public"
server.errorlog = "/var/log/lighttpd/error.log"
server.indexfiles = ("index.php", "index.html")
server.error-handler-404 = "/index.php"

# Rewrite rules for laravel
url.rewrite-if-not-file = (
    "^/favicon.ico$" => "/favicon.ico",
    "^/robots.txt$"  => "/robots.txt",
    "^/(.*)"         => "/index.php/$1"
)

# FastCGI settings for php-fpm
fastcgi.server = ( ".php" =>
    ((
        "socket" => "/run/php-fpm.sock",
        "broken-scriptfilename" => "enable"
    ))
)
~~~

**Comment by huankong233** [comment]
https://laracasts.com/discuss/channels/laravel/lighttpd-setup-for-lararvel-5

这是laravel5的可能不一定有效

**Comment by 1Q23LYC45** [comment]
主目录有个typecho，我给源码放了二级目录，加了伪静态，结果打开的是Typecho的404界面，咋办

**Comment by huankong233** [comment]
源码应该放在和typecho同一级吧，我记得手机上有一个软件，就是一个类似绿色的一本书，可以创建多个网站的，放在一起肯定不行，laravel需要单独一个网站才可以

**Comment by 1Q23LYC45** [comment]
Warning: require(/storage/emulated/0/94speed-laravel/htdocs/public/../vendor/autoload.php): Failed to open stream: No such file or directory in /storage/emulated/0/94speed-laravel/htdocs/public/index.php on line 34

Fatal error: Uncaught Error: Failed opening required '/storage/emulated/0/94speed-laravel/htdocs/public/../vendor/autoload.php' (include_path='.:') in /storage/emulated/0/94speed-laravel/htdocs/public/index.php:34 Stack trace: #0 {main} thrown in /storage/emulated/0/94speed-laravel/htdocs/public/index.php on line 34

**Comment by huankong233** [comment]
哦，你这的环境真不好说，还要手动安装一下composer，这个报错就是你的路径可能不正确，php找不到入口文件 

错误路径: `/storage/emulated/0/94speed-laravel/htdocs/public/index.php`
正确路径: `/storage/emulated/0/94speed-laravel/public/index.php`

**Comment by huankong233** [comment]
> Warning: require(/storage/emulated/0/94speed-laravel/htdocs/public/../vendor/autoload.php): Failed to open stream: No such file or directory in /storage/emulated/0/94speed-laravel/htdocs/public/index.php on line 34
> 
> Fatal error: Uncaught Error: Failed opening required '/storage/emulated/0/94speed-laravel/htdocs/public/../vendor/autoload.php' (include_path='.:') in /storage/emulated/0/94speed-laravel/htdocs/public/index.php:34 Stack trace: #0 {main} thrown in /storage/emulated/0/94speed-laravel/htdocs/public/index.php on line 34

我等下把sqlite搞定发一个完整包给你吧

**Comment by 1Q23LYC45** [comment]
谢谢啦

**Comment by huankong233** [comment]
> 谢谢啦

方便留个邮箱吗

**Comment by 1Q23LYC45** [comment]
> > 谢谢啦
> 
> 方便留个邮箱吗

letter1q23lyc45jtt67z8910zh@outlook.com

**Comment by 1Q23LYC45** [comment]
刚才参考独角发卡的教程运行了命令
cd /storage/emulated/0/94speed-laravel/htdocs
composer install
composer update
然后lighttpd -f /sdcard/94speed-laravel/lighttpd.conf -D运行服务器，出现了报错
500 SERVER ERROR
下面是服务器日志，没看见服务器有内部错误呀（最后两行是我自己关了Lighttpd，不是问题）
2023-09-17 09:14:26: (../src/src/server.c.1909) server started (lighttpd/1.4.71)
2023-09-17 09:14:30: (../src/src/server.c.1216) [note] graceful shutdown started
2023-09-17 09:14:31: (../src/src/server.c.2308) server stopped by UID = 0 PID = 0

**Comment by huankong233** [comment]
> 刚才参考独角发卡的教程运行了命令 cd /storage/emulated/0/94speed-laravel/htdocs composer install composer update 然后lighttpd -f /sdcard/94speed-laravel/lighttpd.conf -D运行服务器，出现了报错 500 SERVER ERROR 下面是服务器日志，没看见服务器有内部错误呀（最后两行是我自己关了Lighttpd，不是问题） 2023-09-17 09:14:26: (../src/src/server.c.1909) server started (lighttpd/1.4.71) 2023-09-17 09:14:30: (../src/src/server.c.1216) [note] graceful shutdown started 2023-09-17 09:14:31: (../src/src/server.c.2308) server stopped by UID = 0 PID = 0 还是请再发一下完整包，我邮箱没收到。 [letter1q23lyc45jtt67z8910zh@outlook.com](mailto:letter1q23lyc45jtt67z8910zh@outlook.com)

你安装了composer吗，我现在在外面，昨天晚上睡觉了，下午晚些时间发给你

**Comment by 1Q23LYC45** [comment]
> > 刚才参考独角发卡的教程运行了命令 cd /storage/emulated/0/94speed-laravel/htdocs composer install composer update 然后lighttpd -f /sdcard/94speed-laravel/lighttpd.conf -D运行服务器，出现了报错 500 SERVER ERROR 下面是服务器日志，没看见服务器有内部错误呀（最后两行是我自己关了Lighttpd，不是问题） 2023-09-17 09:14:26: (../src/src/server.c.1909) server started (lighttpd/1.4.71) 2023-09-17 09:14:30: (../src/src/server.c.1216) [note] graceful shutdown started 2023-09-17 09:14:31: (../src/src/server.c.2308) server stopped by UID = 0 PID = 0 还是请再发一下完整包，我邮箱没收到。 [letter1q23lyc45jtt67z8910zh@outlook.com](mailto:letter1q23lyc45jtt67z8910zh@outlook.com)
> 
> 你安装composer了吗，我现在在外面，昨天晚上睡觉了，下午晚些时间发给你

安装了，(apt install composer)

**Comment by huankong233** [comment]
> > > 刚才参考独角发卡的教程运行了命令 cd /storage/emulated/0/94speed-laravel/htdocs composer install composer update 然后lighttpd -f /sdcard/94speed-laravel/lighttpd.conf -D运行服务器，出现了报错 500 SERVER ERROR 下面是服务器日志，没看见服务器有内部错误呀（最后两行是我自己关了Lighttpd，不是问题） 2023-09-17 09:14:26: (../src/src/server.c.1909) server started (lighttpd/1.4.71) 2023-09-17 09:14:30: (../src/src/server.c.1216) [note] graceful shutdown started 2023-09-17 09:14:31: (../src/src/server.c.2308) server stopped by UID = 0 PID = 0 还是请再发一下完整包，我邮箱没收到。 [letter1q23lyc45jtt67z8910zh@outlook.com](mailto:letter1q23lyc45jtt67z8910zh@outlook.com)
> > 
> > 
> > 你安装composer了吗，我现在在外面，昨天晚上睡觉了，下午晚些时间发给你
> 
> 安装了，(apt install composer)

那可能安装的不是一个conposer，这里的composer是php的依赖安装工具，apt装的貌似不一样，我等下发你，你可以搜一下composer安装

**Comment by 1Q23LYC45** [comment]
腾讯云开发者社区找到一个
https://cloud.tencent.com/developer/article/2267874
安装后，
php composer.phar --version
输出了
Composer version 2.6.3 2023-09-15 09:38:21
是这个吗？

**Comment by huankong233** [comment]
> 腾讯云开发者社区找到一个 https://cloud.tencent.com/developer/article/2267874 安装后， php composer.phar --version 输出了 Composer version 2.6.3 2023-09-15 09:38:21 是这个吗？

有输出那应该就是，你直接composer install就可以安装依赖了，然后再进网站看看

**Comment by huankong233** [comment]
> 腾讯云开发者社区找到一个 https://cloud.tencent.com/developer/article/2267874 安装后， php composer.phar --version 输出了 Composer version 2.6.3 2023-09-15 09:38:21 是这个吗？

https://huankong.top/94list-laravel.7z

完整包

**Comment by huankong233** [comment]
> 腾讯云开发者社区找到一个 https://cloud.tencent.com/developer/article/2267874 安装后， php composer.phar --version 输出了 Composer version 2.6.3 2023-09-15 09:38:21 是这个吗？

https://huankong.top/94list-laravel.7z

完整包

**Comment by 1Q23LYC45** [comment]
> > 腾讯云开发者社区找到一个 https://cloud.tencent.com/developer/article/2267874 安装后， php composer.phar --version 输出了 Composer version 2.6.3 2023-09-15 09:38:21 是这个吗？
> 
> https://huankong.top/94list-laravel.7z
> 
> 完整包

收到，谢谢

**Comment by 1Q23LYC45** [comment]
![Screenshot_20230917_094701_com kiwibrowser browser dev](https://github.com/huankong233/94list-laravel/assets/143373643/b21b12b1-8dac-4795-b42f-959637e41a98)
???啥情况？
伪静态已配置。
访问日志：
127.0.0.1 127.0.0.1:8081 - [17/Sep/2023:09:46:56 +0800] "GET / HTTP/1.1" 500 13218 "-" "Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.0.0 Mobile Safari/537.36"
错误日志：
2023-09-17 09:46:55: (../src/src/server.c.1909) server started (lighttpd/1.4.71)

**Comment by huankong233** [comment]
> ![Screenshot_20230917_094701_com kiwibrowser browser dev](https://user-images.githubusercontent.com/143373643/268478313-b21b12b1-8dac-4795-b42f-959637e41a98.jpg) ???啥情况？ 伪静态已配置。 访问日志： 127.0.0.1 127.0.0.1:8081 - [17/Sep/2023:09:46:56 +0800] "GET / HTTP/1.1" 500 13218 "-" "Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.0.0 Mobile Safari/537.36" 错误日志： 2023-09-17 09:46:55: (../src/src/server.c.1909) server started (lighttpd/1.4.71)

伪静态生效了，打开.env文件，把app_debug的值改为true，然后看看报错是啥

**Comment by 1Q23LYC45** [comment]
> > ![Screenshot_20230917_094701_com kiwibrowser browser dev](https://user-images.githubusercontent.com/143373643/268478313-b21b12b1-8dac-4795-b42f-959637e41a98.jpg) ???啥情况？ 伪静态已配置。 访问日志： 127.0.0.1 127.0.0.1:8081 - [17/Sep/2023:09:46:56 +0800] "GET / HTTP/1.1" 500 13218 "-" "Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.0.0 Mobile Safari/537.36" 错误日志： 2023-09-17 09:46:55: (../src/src/server.c.1909) server started (lighttpd/1.4.71)
> 
> 伪静态生效了，打开.env文件，把app_debug的值改为true，然后看看报错是啥

没找到.env文件。

**Comment by huankong233** [comment]
> > > ![Screenshot_20230917_094701_com kiwibrowser browser dev](https://user-images.githubusercontent.com/143373643/268478313-b21b12b1-8dac-4795-b42f-959637e41a98.jpg) ???啥情况？ 伪静态已配置。 访问日志： 127.0.0.1 127.0.0.1:8081 - [17/Sep/2023:09:46:56 +0800] "GET / HTTP/1.1" 500 13218 "-" "Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.0.0 Mobile Safari/537.36" 错误日志： 2023-09-17 09:46:55: (../src/src/server.c.1909) server started (lighttpd/1.4.71)
> > 
> > 
> > 伪静态生效了，打开.env文件，把app_debug的值改为true，然后看看报错是啥
> 
> 没找到.env文件。

那可能是我打包的时候没打进去所以导致了报错😂，我重新搞一下等一下

**Comment by huankong233** [comment]
> > > ![Screenshot_20230917_094701_com kiwibrowser browser dev](https://user-images.githubusercontent.com/143373643/268478313-b21b12b1-8dac-4795-b42f-959637e41a98.jpg) ???啥情况？ 伪静态已配置。 访问日志： 127.0.0.1 127.0.0.1:8081 - [17/Sep/2023:09:46:56 +0800] "GET / HTTP/1.1" 500 13218 "-" "Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.0.0 Mobile Safari/537.36" 错误日志： 2023-09-17 09:46:55: (../src/src/server.c.1909) server started (lighttpd/1.4.71)
> > 
> > 
> > 伪静态生效了，打开.env文件，把app_debug的值改为true，然后看看报错是啥
> 
> 没找到.env文件。

我给你分享了文件，取件码：22851，https://temp.huankong.top/?code=22851

**Comment by huankong233** [comment]
> > > ![Screenshot_20230917_094701_com kiwibrowser browser dev](https://user-images.githubusercontent.com/143373643/268478313-b21b12b1-8dac-4795-b42f-959637e41a98.jpg) ???啥情况？ 伪静态已配置。 访问日志： 127.0.0.1 127.0.0.1:8081 - [17/Sep/2023:09:46:56 +0800] "GET / HTTP/1.1" 500 13218 "-" "Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.0.0 Mobile Safari/537.36" 错误日志： 2023-09-17 09:46:55: (../src/src/server.c.1909) server started (lighttpd/1.4.71)
> > 
> > 
> > 伪静态生效了，打开.env文件，把app_debug的值改为true，然后看看报错是啥
> 
> 没找到.env文件。

启动成功了吗，现在支持sqlite了，应该可以直接输几个环境变量就可以启用了，如果有报错再和我说吧

**Comment by 1Q23LYC45** [comment]
已解决，感谢大佬的不懈努力

**Comment by huankong233** [comment]
> 已解决，感谢大佬的不懈努力

不用谢🤗
