### ISSUE TITLE
有关账号限制下载频率的问题

### ISSUE THREAD

**Issue by Zxis233** [huankong233/94list-laravel#40]
请问，百度网盘超级会员的账号是否会对一段时间内的下载频率做限制？比如一天内最多进行50次解析
因为本人有大量文件需下载，同时希望尽可能让账号Cookie存活

**Comment by huankong233** [comment]
> 请问，百度网盘超级会员的账号是否会对一段时间内的下载频率做限制？比如一天内最多进行50次解析 因为本人有大量文件需下载，同时希望尽可能让账号Cookie存活

会限制的，而且对下载文件的总大小也有限制

**Comment by Zxis233** [comment]
感谢解答。
