### ISSUE TITLE
能否支持Motrix下载

### ISSUE THREAD

**Issue by JsBeta** [huankong233/94list-laravel#41]
Motrix下载能否支持一下

**Comment by huankong233** [comment]
> Motrix下载能否支持一下

motrix是基于Aria2的只需要修改Aria2中的地址,端口密钥为正确的值保存即可

**Comment by huankong233** [comment]
> > Motrix下载能否支持一下
> 
> motrix是基于Aria2的只需要修改Aria2设置中的地址,端口密钥为Motrix的值保存即可

**Comment by JsBeta** [comment]
![image](https://github.com/huankong233/94list-laravel/assets/38424690/bb3fab48-b63e-43eb-ab05-96fecb2e006b)
请问如何在解析任务列表这里添加一个发送到Motrix的快捷方式呀

**Comment by huankong233** [comment]
> ![image](https://private-user-images.githubusercontent.com/38424690/299206370-bb3fab48-b63e-43eb-ab05-96fecb2e006b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYwODU0NDAsIm5iZiI6MTcwNjA4NTE0MCwicGF0aCI6Ii8zODQyNDY5MC8yOTkyMDYzNzAtYmIzZmFiNDgtYjYzZS00M2ViLWFiMDUtOTZmZWNiMmUwMDZiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI0VDA4MzIyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBmMTZjNWIzYTJiY2M0MzQ1N2UzNmUxMDhjYjVjMTU2OWJjMDM5YjEzOTMyMzM5MjM0YTM3YjMxZjY4MWYyZTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9DRwHWDUVpvN9he3frtqBe7Vr3TZJgJQPx75-k-mRc8) 请问如何在解析任务列表这里添加一个发送到Motrix的快捷方式呀

个人觉得没有这个必要，如果需要的话，可以到 [94list-laravel-frontend](https://github.com/huankong233/94list-laravel-frontend) 中修改

下载弹窗的代码位置: https://github.com/huankong233/94list-laravel-frontend/blob/main/src/components/UserPannel/downloadDialog.vue

**Comment by JsBeta** [comment]
好的，谢谢楼主
