### ISSUE TITLE
登录上后一秒就过期了

### ISSUE THREAD

**Issue by 1Q23LYC45** [huankong233/94list-laravel#43]
？
登录管理后台加载一秒就自动退出，上面弹出登录已过期。
浏览器Chrome 98.0.4758.51，怎么办

**Comment by huankong233** [comment]
> ？ 登录管理后台加载一秒就自动退出，上面弹出登录已过期。 浏览器Chrome 98.0.4758.51，怎么办

🤔应该是session没存上，没root有些文件存不下来

**Comment by huankong233** [comment]
> > ？ 登录管理后台加载一秒就自动退出，上面弹出登录已过期。 浏览器Chrome 98.0.4758.51，怎么办
> 
> 🤔应该是session没存上，没root有些文件存不下来

https://blog.csdn.net/fjnjxr/article/details/119874527

看看有文件没

**Comment by 1Q23LYC45** [comment]
session.save_path => no value => no value，不过Typecho能登录啊，怎么回事？

**Comment by 1Q23LYC45** [comment]
手动设置session.save_path=/data/data/com.termux/cache，也没用。还是那样。

**Comment by huankong233** [comment]
> session.save_path => no value => no value，不过Typecho能登录啊，怎么回事？

前面一直在忙，我的意思是让你检查一下那个路径里是否有多出来的文件，比如说你先把路径里清空，然后登陆，登陆了之后有多的文件没有

**Comment by huankong233** [comment]
> 手动设置session.save_path=/data/data/com.termux/cache，也没用。还是那样。

有 cookieEditor 吗，是不是服务器发送的 setCookie 操作被浏览器忽略了也有可能

**Comment by huankong233** [comment]
> > 手动设置session.save_path=/data/data/com.termux/cache，也没用。还是那样。
> 
> 有 cookieEditor 吗，是不是服务器发送的 setCookie 操作被浏览器忽略了也有可能

![image](https://github.com/huankong233/94list-laravel/assets/49610758/5d665218-776c-4c4b-8a06-252b9b748a3a)

需要有这个字段才行

**Comment by 1Q23LYC45** [comment]
没有文件，但是cookie有一个94list_laravel_什么东西，缺两个。
![Screenshot_20240127_173611](https://github.com/huankong233/94list-laravel/assets/143373643/74cc4fe8-f8dc-4f68-97c0-911c17ddad32)

**Comment by huankong233** [comment]
> 没有文件，但是cookie有一个94list_laravel_什么东西，缺两个。 ![Screenshot_20240127_173611](https://private-user-images.githubusercontent.com/143373643/300170433-74cc4fe8-f8dc-4f68-97c0-911c17ddad32.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYzNTA5MzUsIm5iZiI6MTcwNjM1MDYzNSwicGF0aCI6Ii8xNDMzNzM2NDMvMzAwMTcwNDMzLTc0Y2M0ZmU4LWY4ZGMtNGY2OC05N2MwLTkxMWMxN2RkYWQzMi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyN1QxMDE3MTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01NDZhOTllNGEzNTYxNzIzOWM2ZTk4NjZiOGY1MDJlYzQzM2M3ZWUzNDIzYjc0NDJjNjE4MmNhOTY4NzkxNTk1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.F7VSZ8BERZh_AvMIpXxIphKKw41e016LTKwhud_EkRM) 那个什么东西是session没错。

那两个是我本地用的，不是必备，但是 `94list-laravel-session` 是必须的

**Comment by huankong233** [comment]
> 没有文件，但是cookie有一个94list_laravel_什么东西，缺两个。 ![Screenshot_20240127_173611](https://private-user-images.githubusercontent.com/143373643/300170433-74cc4fe8-f8dc-4f68-97c0-911c17ddad32.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYzNTA5MzUsIm5iZiI6MTcwNjM1MDYzNSwicGF0aCI6Ii8xNDMzNzM2NDMvMzAwMTcwNDMzLTc0Y2M0ZmU4LWY4ZGMtNGY2OC05N2MwLTkxMWMxN2RkYWQzMi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyN1QxMDE3MTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01NDZhOTllNGEzNTYxNzIzOWM2ZTk4NjZiOGY1MDJlYzQzM2M3ZWUzNDIzYjc0NDJjNjE4MmNhOTY4NzkxNTk1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.F7VSZ8BERZh_AvMIpXxIphKKw41e016LTKwhud_EkRM) 那个什么东西是session没错。

如果没有文件，那就说明文件保存失败了，问一下你是直接在 `termux` 里部署的 还是用的 `proot` 环境，我可以试试看能不能复现，今天正好在研究 `termux`

**Comment by 1Q23LYC45** [comment]
Termux原生环境。

**Comment by 1Q23LYC45** [comment]
Proot应该没事。只要配置ok就行。刚才一直给电脑装显卡驱动，没看到。

**Comment by huankong233** [comment]
> Termux原生环境。

🤧

**Comment by 1Q23LYC45** [comment]
> > Termux原生环境。
> 
> 🤧

?????????????????????????????????????
（Proot里的Kali Linux确实没问题，直接用Termux装才这样）

**Comment by huankong233** [comment]
> > > Termux原生环境。
> > 
> > 
> > 🤧
> 
> ????????????????????????????????????? （Proot里的Kali Linux确实没问题，直接用Termux装才这样）

那说明多半不是我代码的问题了🤧

**Comment by huankong233** [comment]
> > > > Termux原生环境。
> > > 
> > > 
> > > 🤧
> > 
> > 
> > ????????????????????????????????????? （Proot里的Kali Linux确实没问题，直接用Termux装才这样）
> 
> 那说明多半不是我代码的问题了🤧

但是typecho是可以的对吧

**Comment by 1Q23LYC45** [comment]
Typecho可以，wordpress都能行，原版94list也能用（不过得另弄一个mysql）

**Comment by 1Q23LYC45** [comment]
不弄了，proot跑吧（系统限制）。
