### ISSUE TITLE
关于更新方式的问题

### ISSUE THREAD

**Issue by Zxis233** [huankong233/94list-laravel#45]
请问直接Git Pull可以更新吗？是否会覆盖先前的配置？

**Comment by huankong233** [comment]
> 请问直接Git Pull可以更新吗？是否会覆盖先前的配置？

推荐使用 `docker` 部署，更新起来会更方便，无伤

https://github.com/huankong233/94list-laravel/blob/main/docker/entrypoint.sh

这是启动脚本，里面包含了更新时需要进行的操作，一般情况下只需要更新了代码，然后执行 `php artisan app:check-app-status` 即可

**Comment by Zxis233** [comment]
> > 请问直接Git Pull可以更新吗？是否会覆盖先前的配置？
> 
> 推荐使用 `docker` 部署，更新起来会更方便，无伤
> 
> https://github.com/huankong233/94list-laravel/blob/main/docker/entrypoint.sh
> 
> 这是启动脚本，里面包含了更新时需要进行的操作，一般情况下只需要更新了代码，然后执行 `php artisan app:check-app-status` 即可

收到，感谢解答。

**Comment by Zxis233** [comment]
不知道为什么，替换文件后链接原来的数据库会提示数据表格式错误，只能重新添加了一遍用户。

**Comment by huankong233** [comment]
> 不知道为什么，替换文件后链接原来的数据库会提示数据表格式错误，只能重新添加了一遍用户。

🤔有详细的报错吗，感觉手动更新还是会有些麻烦，有空优化一下吧，那个命令不能直接用，可能有问题

**Comment by Zxis233** [comment]
坏了，忘记截图了😢
有办法看历史日志吗

**Comment by huankong233** [comment]
> 坏了，忘记截图了😢 有办法看历史日志吗

logs文件夹里

**Comment by Zxis233** [comment]
> > 坏了，忘记截图了😢 有办法看历史日志吗
> 
> logs文件夹里

文件夹是空的
```bash
╭─zxis@LittleBox ~/94list-laravel/storage/logs ‹main●›
╰─$ ll
总计 0
```

**Comment by huankong233** [comment]
> > > 坏了，忘记截图了😢 有办法看历史日志吗
> > 
> > 
> > logs文件夹里
> 
> 文件夹是空的
> 
> ```shell
> ╭─zxis@LittleBox ~/94list-laravel/storage/logs ‹main●›
> ╰─$ ll
> 总计 0
> ```

🤔那算了，因为其实有一次更新把表结构破坏了来着，可能你是那次版本之前的，那几个版本的包我也都撤了已经
