### ISSUE TITLE
大佬你好，我看你主页说参考那个独角数卡来安装，但是始终安装不了

### ISSUE THREAD

**Issue by iuiuiu123234** [huankong233/94list-laravel#46]
都是显示已停止，怎么重启都无效这是什么原因呢？
<img width="734" alt="1" src="https://github.com/huankong233/94list-laravel/assets/157090716/7a7bbd67-8a1e-4c36-9a9a-41d7459742d5">
<img width="734" alt="1" src="https://github.com/huankong233/94list-laravel/assets/157090716/2f520e81-14b7-4111-a1cf-93a1e94d995c">

**Comment by iuiuiu123234** [comment]
我用的是堡塔 PHP是8.1

**Comment by huankong233** [comment]
忘记写了，不好意思 : )

**Comment by iuiuiu123234** [comment]
那大佬 这个堡塔该如何安装这个源码呢？可以大概说一下步骤吗
