### ISSUE TITLE
大佬 用堡塔该如何安装这个源码呢？可以大概说一下步骤吗

### ISSUE THREAD

**Issue by iuiuiu123234** [huankong233/94list-laravel#48]

**Comment by huankong233** [comment]
release里下载压缩包，解压后设置好运行目录为public即可，记得设置几个函数从禁用列表里移除

**Comment by iuiuiu123234** [comment]
<img width="872" alt="1" src="https://github.com/huankong233/94list-laravel/assets/157090716/b71a7a62-3f66-481c-950e-b16121ebfc38">

**Comment by iuiuiu123234** [comment]
移除了呀 然后提示这个

**Comment by iuiuiu123234** [comment]
putenv，proc_open，pcntl_signal，pcntl_alarm 我按照独角数卡 然后移除这几个 然后安装了几个扩展 按照独角数卡那样整

**Comment by huankong233** [comment]
> putenv，proc_open，pcntl_signal，pcntl_alarm 我按照独角数卡 然后移除这几个 然后安装了几个扩展 按照独角数卡那样整

可以下release里的，源码需要自己用composer装依赖

**Comment by iuiuiu123234** [comment]
<img width="550" alt="1" src="https://github.com/huankong233/94list-laravel/assets/157090716/85b396f9-b670-467f-a67f-43f090a0baf2">
是按照这个来修改吗

**Comment by huankong233** [comment]
> <img alt="1" width="550" src="https://private-user-images.githubusercontent.com/157090716/304064479-85b396f9-b670-467f-a67f-43f090a0baf2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc3NDA1NTksIm5iZiI6MTcwNzc0MDI1OSwicGF0aCI6Ii8xNTcwOTA3MTYvMzA0MDY0NDc5LTg1YjM5NmY5LWI2NzAtNDY3Zi1hNjdmLTQzZjA5MGEwYmFmMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxMlQxMjE3MzlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hOWIwMjE2NTQyOGY2NTNiNWVmNzQ4M2NhYzJkN2UwOGYxYjAxZTRlMjcxODRmNTQ1NjNhN2JkNjg4YTY4ODQyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Za7OACeaq2EegL_PMYABI2ICqiFFbygnc-ClYuoPSzE"> 是按照这个来修改吗

这个是 docker-compose ，我说的是 composer ，是一个php的依赖管理工具

**Comment by huankong233** [comment]
> <img alt="1" width="550" src="https://private-user-images.githubusercontent.com/157090716/304064479-85b396f9-b670-467f-a67f-43f090a0baf2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc3NDA1NTksIm5iZiI6MTcwNzc0MDI1OSwicGF0aCI6Ii8xNTcwOTA3MTYvMzA0MDY0NDc5LTg1YjM5NmY5LWI2NzAtNDY3Zi1hNjdmLTQzZjA5MGEwYmFmMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxMlQxMjE3MzlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hOWIwMjE2NTQyOGY2NTNiNWVmNzQ4M2NhYzJkN2UwOGYxYjAxZTRlMjcxODRmNTQ1NjNhN2JkNjg4YTY4ODQyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Za7OACeaq2EegL_PMYABI2ICqiFFbygnc-ClYuoPSzE"> 是按照这个来修改吗

是给docker安装的用户用的

**Comment by iuiuiu123234** [comment]
大佬  有准备出个安装教程吗？
