### ISSUE TITLE
大佬 现在有个新问题，就是搭建好了 在后台修改配置报错，然后无法修改后台设置

### ISSUE THREAD

**Issue by iuiuiu123234** [huankong233/94list-laravel#49]
![1](https://github.com/huankong233/94list-laravel/assets/157090716/c8d1cc0c-da16-4e96-9dc2-cb9e3e65a2e7)

**Comment by iuiuiu123234** [comment]
搭建在linux可以用，搭在windows就报这个错误
![1](https://github.com/huankong233/94list-laravel/assets/157090716/69461e48-b6ad-4357-aa60-159a99a1eab4)

**Comment by huankong233** [comment]
> 搭建在linux可以用，搭在windows就报这个错误 ![1](https://private-user-images.githubusercontent.com/157090716/304265915-69461e48-b6ad-4357-aa60-159a99a1eab4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc3ODcxNjYsIm5iZiI6MTcwNzc4Njg2NiwicGF0aCI6Ii8xNTcwOTA3MTYvMzA0MjY1OTE1LTY5NDYxZTQ4LWI2YWQtNDM1Ny1hYTYwLTE1OWE5OWExZWFiNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxM1QwMTE0MjZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04NTIxZWMxYzgyY2FjZDNkN2M2Mzg3ZjI0Mjg4ZmUxZjVkNjMyMWI4MzMyNWMwZjVmMGYzMWU2OWI0MTVhMDgxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9._athVibYHk3k3canQwYBKtSX07Cd1vBy54tB2jKakAE)

🤔 应该不会，我是在windows进行开发的，linux有问题windows也不会有问题啊，去项目目录，在
.env文件里把调试模式打开，然后在f12里看看详细报错

**Comment by iuiuiu123234** [comment]
windows上搭建请求显示500
![1](https://github.com/huankong233/94list-laravel/assets/157090716/1146633c-cc44-4395-8563-047c3e2a4ad2)
![2](https://github.com/huankong233/94list-laravel/assets/157090716/9e5b1ce1-b805-4cd6-9d3d-0b092122d6d3)

**Comment by huankong233** [comment]
> windows上搭建请求显示500 ![1](https://private-user-images.githubusercontent.com/157090716/304935980-1146633c-cc44-4395-8563-047c3e2a4ad2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc5NjY0NjEsIm5iZiI6MTcwNzk2NjE2MSwicGF0aCI6Ii8xNTcwOTA3MTYvMzA0OTM1OTgwLTExNDY2MzNjLWNjNDQtNDM5NS04NTYzLTA0N2MzZTJhNGFkMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxNVQwMzAyNDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jMTI1OTU4MTZmZjkyYjY4OThmYmQxMTg5ZTc3MjBjZWVlMTEyZWE4ZmRmNGU3YzEyNTU0ZDE4OTY2OWNiMjE5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.nGsm10E5wVTdkljYO8gaEdzc7S7umw2BEuP2RxA_5Es) ![2](https://private-user-images.githubusercontent.com/157090716/304935999-9e5b1ce1-b805-4cd6-9d3d-0b092122d6d3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc5NjY0NjEsIm5iZiI6MTcwNzk2NjE2MSwicGF0aCI6Ii8xNTcwOTA3MTYvMzA0OTM1OTk5LTllNWIxY2UxLWI4MDUtNGNkNi05ZDNkLTBiMDkyMTIyZDZkMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxNVQwMzAyNDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04ZjM4ZWVhNDA1NTRmNWMxZmMzNTVhZTgwODI3YTA1ZGFhYzk4NGJjYTUyYmNhY2IzOWNjNGNkYTliN2VkYTI1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.jCzx2LFdeJxc6TwsqjUD2QsNlPPASXEKt7Q04xnPXSA)

换个ip试试，可能被屏蔽了

**Comment by iuiuiu123234** [comment]
对的 linux正常 windows不行

**Comment by iuiuiu123234** [comment]
换ip也不行欸

**Comment by iuiuiu123234** [comment]
是不是php配置不一样呀

**Comment by huankong233** [comment]
> 对的 linux正常 windows不行

是同一台设备吗

**Comment by iuiuiu123234** [comment]
对的

**Comment by huankong233** [comment]
> 对的

都是源码安装的是吧

**Comment by iuiuiu123234** [comment]
对的呀

**Comment by iuiuiu123234** [comment]
同一套源码

**Comment by iuiuiu123234** [comment]
就是主页发布的安装好依赖的那个源码

**Comment by huankong233** [comment]
在这里 https://github.com/huankong233/94list-laravel/blob/main/app/Http/Controllers/AdminController.php#L236

加一句

~~~ php
dd($response);
~~~

然后重新重复操作，看看输出

**Comment by iuiuiu123234** [comment]
然后下载下来没有依赖 然后自己安装了依赖

**Comment by huankong233** [comment]
> 然后下载下来没有依赖 然后自己安装了依赖

草，忘记传了，只有源码在里面

**Comment by iuiuiu123234** [comment]
好的 我试试 谢谢大佬

**Comment by huankong233** [comment]
> 好的 我试试 谢谢大佬

先试试看我上面那个代码加上会有什么报错

**Comment by iuiuiu123234** [comment]
加在236行 没有输出 然后加载230行报这个错误
![1](https://github.com/huankong233/94list-laravel/assets/157090716/038336e1-437b-4c68-af67-44d4e935fe18)
![2](https://github.com/huankong233/94list-laravel/assets/157090716/906802df-a967-4ad9-b77d-84c392a1d490)

**Comment by huankong233** [comment]
> 加在236行 没有输出 然后加载230行报这个错误 ![1](https://private-user-images.githubusercontent.com/157090716/305057307-038336e1-437b-4c68-af67-44d4e935fe18.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc5OTcwMzQsIm5iZiI6MTcwNzk5NjczNCwicGF0aCI6Ii8xNTcwOTA3MTYvMzA1MDU3MzA3LTAzODMzNmUxLTQzN2ItNGM2OC1hZjY3LTQ0ZDRlOTM1ZmUxOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxNVQxMTMyMTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02M2ViNzBmNmM0ODk2NjRmZGQ0M2Y1NGU2Mjk5OGMzMDQ2YzUxZTZmYjcxODUyYTQ5ZWU2YWNhZmQxZjM3YjExJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.SeUC1v-Q_YZvM1gEHKudkewxFDi4EiMwcVw57-anT24) ![2](https://private-user-images.githubusercontent.com/157090716/305057437-906802df-a967-4ad9-b77d-84c392a1d490.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc5OTcwMzQsIm5iZiI6MTcwNzk5NjczNCwicGF0aCI6Ii8xNTcwOTA3MTYvMzA1MDU3NDM3LTkwNjgwMmRmLWE5NjctNGFkOS1iNzdkLTg0YzM5MmExZDQ5MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxNVQxMTMyMTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03OWNhYmE2ZDMzOTM2MWJiMGJhNDE1MDZkYjJkMmE1YmNlZGMzZWQwMzYyNDgzNjZhZWY1YTUxYjg4MDhjZTZmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.vSk2dwwaJFjnzn02KSPyXro4i3TeP95inAnVdNnUSio)

不要在那里放，把代码放到 246 行,试试看 `dd($response->getResponse());` 

感觉可能是请求失败了，可能是扩展还是什么有问题

**Comment by huankong233** [comment]
> > 加在236行 没有输出 然后加载230行报这个错误 ![1](https://private-user-images.githubusercontent.com/157090716/305057307-038336e1-437b-4c68-af67-44d4e935fe18.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc5OTcwMzQsIm5iZiI6MTcwNzk5NjczNCwicGF0aCI6Ii8xNTcwOTA3MTYvMzA1MDU3MzA3LTAzODMzNmUxLTQzN2ItNGM2OC1hZjY3LTQ0ZDRlOTM1ZmUxOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxNVQxMTMyMTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02M2ViNzBmNmM0ODk2NjRmZGQ0M2Y1NGU2Mjk5OGMzMDQ2YzUxZTZmYjcxODUyYTQ5ZWU2YWNhZmQxZjM3YjExJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.SeUC1v-Q_YZvM1gEHKudkewxFDi4EiMwcVw57-anT24) ![2](https://private-user-images.githubusercontent.com/157090716/305057437-906802df-a967-4ad9-b77d-84c392a1d490.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc5OTcwMzQsIm5iZiI6MTcwNzk5NjczNCwicGF0aCI6Ii8xNTcwOTA3MTYvMzA1MDU3NDM3LTkwNjgwMmRmLWE5NjctNGFkOS1iNzdkLTg0YzM5MmExZDQ5MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxNVQxMTMyMTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03OWNhYmE2ZDMzOTM2MWJiMGJhNDE1MDZkYjJkMmE1YmNlZGMzZWQwMzYyNDgzNjZhZWY1YTUxYjg4MDhjZTZmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.vSk2dwwaJFjnzn02KSPyXro4i3TeP95inAnVdNnUSio)
> 
> 不要在那里放，把代码放到 236 行,试试看 `dd($response->getResponse());`
> 
> 感觉可能是请求失败了，可能是扩展还是什么有问题

**Comment by iuiuiu123234** [comment]
大佬 我看你乖乖上传的源码 那个是传好依赖的吗

**Comment by iuiuiu123234** [comment]
大佬 我看你刚刚新的源码 是传好依赖的吗

**Comment by huankong233** [comment]
> 大佬 我看你刚刚新的源码 是传好依赖的吗

是的哦，或者留个qq远程看一下什么问题

**Comment by iuiuiu123234** [comment]
1339567919

**Comment by huankong233** [comment]
用户使用的 `windows` 未包含最新的 CA证书 导致请求 百度服务器出现问题

按照教程已修复

https://www.cnblogs.com/aze999/p/15048366.html
