### ISSUE TITLE
SSH内网穿透时出现端口漂移，Frp正常(已解决)

### ISSUE THREAD

**Issue by 1Q23LYC45** [huankong233/94list-laravel#5]
在使用基于ssh客户端的内网穿透（内网云，Serveo，LocalhostRun）时，解析列表一直转圈卡死，控制台输出了 post https://127.0.0.1:18111/api/user/getfilelist net:err:connection:refused  
我的服务器地址不是127.0.0.1:18111而是127.0.0.1：8081
但我使用Frpc加自己的域名方案却一切正常。

**Comment by huankong233** [comment]
> 在使用基于ssh客户端的内网穿透（内网云，Serveo，LocalhostRun）时，解析列表一直转圈卡死，控制台输出了 post https://127.0.0.1:18111/api/user/getfilelist net:err:connection:refused 我的服务器地址不是127.0.0.1:18111而是127.0.0.1：8081 但我使用Frpc加自己的域名方案却一切正常。

![image](https://github.com/huankong233/94list-laravel/assets/49610758/a21277dd-5549-45e8-9b19-d505e1d09527)
检查这个的值

**Comment by huankong233** [comment]
> 在使用基于ssh客户端的内网穿透（内网云，Serveo，LocalhostRun）时，解析列表一直转圈卡死，控制台输出了 post https://127.0.0.1:18111/api/user/getfilelist net:err:connection:refused 我的服务器地址不是127.0.0.1:18111而是127.0.0.1：8081 但我使用Frpc加自己的域名方案却一切正常。

应该是laravel那边的ip是按照你转发层设置的内网ip来生成的地址🧐，我想想怎么解决

**Comment by huankong233** [comment]
> 在使用基于ssh客户端的内网穿透（内网云，Serveo，LocalhostRun）时，解析列表一直转圈卡死，控制台输出了 post https://127.0.0.1:18111/api/user/getfilelist net:err:connection:refused 我的服务器地址不是127.0.0.1:18111而是127.0.0.1：8081 但我使用Frpc加自己的域名方案却一切正常。

我把路由地址改为相对路径了，应该可以解决

我给你分享了文件，取件码：10653，https://temp.huankong.top/?code=10653

**Comment by huankong233** [comment]
> 在使用基于ssh客户端的内网穿透（内网云，Serveo，LocalhostRun）时，解析列表一直转圈卡死，控制台输出了 post https://127.0.0.1:18111/api/user/getfilelist net:err:connection:refused 我的服务器地址不是127.0.0.1:18111而是127.0.0.1：8081 但我使用Frpc加自己的域名方案却一切正常。

可以了吗

**Comment by 1Q23LYC45** [comment]
抱歉，刚才做PPT去了。现在我试一下。

**Comment by huankong233** [comment]
> 抱歉，刚才做PPT去了。现在我试一下。

好的

**Comment by 1Q23LYC45** [comment]
可以用了，谢谢！
