### ISSUE TITLE
新增功能

### ISSUE THREAD

**Issue by wqerzc** [huankong233/94list-laravel#50]
怎么添加限制次数呢，想https://58.87.88.194/这个一样

**Comment by huankong233** [comment]
> 怎么添加限制次数呢，想[https://58.87.88.194/这个一样](https://58.87.88.194/%E8%BF%99%E4%B8%AA%E4%B8%80%E6%A0%B7)

打不开呢

**Comment by candies404** [comment]
https://58.87.88.194/ 可以打开啊

**Comment by huankong233** [comment]
> https://58.87.88.194/ 可以打开啊

现在可以，之前一直卡加载，没反应

**Comment by candies404** [comment]
> > https://58.87.88.194/ 可以打开啊
> 
> 现在可以，之前一直卡加载，没反应

好的，能否添加这个功能呢

**Comment by huankong233** [comment]
> 怎么添加限制次数呢，想[https://58.87.88.194/这个一样](https://58.87.88.194/%E8%BF%99%E4%B8%AA%E4%B8%80%E6%A0%B7)

在这里加上对应逻辑吧，因为需要记录使用者信息，所以不会在官方版本增加这个功能

https://github.com/huankong233/94list-laravel/blob/5172b820e0ef5618dd93485dfa189629f95d8816/app/Http/Controllers/UserController.php#L231-L408

**Comment by huankong233** [comment]
> > > https://58.87.88.194/ 可以打开啊
> > 
> > 
> > 现在可以，之前一直卡加载，没反应
> 
> 好的，能否添加这个功能呢

我不会加

**Comment by candies404** [comment]
好的

**Comment by huankong233** [comment]
1.0版本中已添加
