### ISSUE TITLE
疑似无法链接Aria2的端口，无法连接

### ISSUE THREAD

**Issue by MoTeam-org** [huankong233/94list-laravel#54]
在测试过程中发现，在发送Aria2的6800端口时无法发送，似乎是Js脚本问题，还是CORS问题

**Comment by huankong233** [comment]
> 在测试过程中发现，在发送Aria2的6800端口时无法发送，似乎是Js脚本问题，还是CORS问题

aria2的接口我记得cors是不受限制的，应该是chrome的https安全策略，提供一下控制台报错

**Comment by MoTeam-org** [comment]
刚才再次测试发现，ws链接就没有问题，Http就会出问题，这很奇怪

**Comment by huankong233** [comment]
> 刚才再次测试发现，ws链接就没有问题，Http就会出问题，这很奇怪

https://github.com/codehub666/94list/issues/25#issuecomment-1718914514

检查一下是不是这个问题

**Comment by huankong233** [comment]
https://github.com/codehub666/94list/issues/27

**Comment by MoTeam-org** [comment]
测试发现，Http也就是CORS问题
![image](https://github.com/huankong233/94list-laravel/assets/112475198/83eb7210-9bb5-4c8d-992a-46a0223414ac)

**Comment by huankong233** [comment]
> 测试发现，Http也就是CORS问题 ![image](https://private-user-images.githubusercontent.com/112475198/319429326-83eb7210-9bb5-4c8d-992a-46a0223414ac.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIyMDA4MDUsIm5iZiI6MTcxMjIwMDUwNSwicGF0aCI6Ii8xMTI0NzUxOTgvMzE5NDI5MzI2LTgzZWI3MjEwLTliYjUtNGM4ZC05OTJhLTQ2YTAyMjM0MTRhYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwNFQwMzE1MDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lZmVmNDNiOWMwMDRhNzk3ODM2ZWFmMzRlZDk0Mjc2MGJhMWMyYzQ2ZWNmMjkwODNmOWI1OTE3NmMwYTVmYTM5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.H2c7qvYbVcEnUrn8lrsEk0NmBUG5KYZWzCiR0IElh_4)

类似问题: https://github.com/mayswind/AriaNg/issues/46

**Comment by MoTeam-org** [comment]
然而我的是整合程序，没有任何配置文件
![image](https://github.com/huankong233/94list-laravel/assets/112475198/7b1b40fc-cb03-4ee0-9e6d-c7cd2618632c)

**Comment by huankong233** [comment]
> 然而我的是整合程序，没有任何配置文件 ![image](https://private-user-images.githubusercontent.com/112475198/319430110-7b1b40fc-cb03-4ee0-9e6d-c7cd2618632c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIyMDEwNzEsIm5iZiI6MTcxMjIwMDc3MSwicGF0aCI6Ii8xMTI0NzUxOTgvMzE5NDMwMTEwLTdiMWI0MGZjLWNiMDMtNGVlMC05ZTZkLWM3Y2QyNjE4NjMyYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwNFQwMzE5MzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kOTA4NWFlNjg1ZTU1MmQzYjk2NjcwZTZiOGFlMzA3NGJkNjk2OTdmM2IxNGMwYzY4NjQxZTU4M2JlM2IxYzE4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.aZ4WpPRAiG_e0RdPtAF5AIUuiYlR0C1nuPpbgTwOJ74)

直接加启动项试试呢，这个问题不是我这的问题了
