### ISSUE TITLE
这个软件最小支持PHP版本多少？

### ISSUE THREAD

**Issue by 1Q23LYC45** [huankong233/94list-laravel#6]
如题。最近从Termux迁移到KSWeb报错了。  
nginx/1.20.1，PHP8.0.6。  
```
Fatal error: Composer detected issues in your platform: Your Composer dependencies require a PHP version ">= 8.1.0". You are running 8.0.6. in /storage/emulated/0/htdocs/94speed-laravel/vendor/composer/platform_check.php on line 24
```

**Comment by huankong233** [comment]
> 如题。最近从Termux迁移到KSWeb报错了。 nginx/1.20.1，PHP8.0.6。
> 
> ```
> Fatal error: Composer detected issues in your platform: Your Composer dependencies require a PHP version ">= 8.1.0". You are running 8.0.6. in /storage/emulated/0/htdocs/94speed-laravel/vendor/composer/platform_check.php on line 24
> ```

php需要≥8.1

**Comment by huankong233** [comment]
> 如题。最近从Termux迁移到KSWeb报错了。 nginx/1.20.1，PHP8.0.6。
> 
> ```
> Fatal error: Composer detected issues in your platform: Your Composer dependencies require a PHP version ">= 8.1.0". You are running 8.0.6. in /storage/emulated/0/htdocs/94speed-laravel/vendor/composer/platform_check.php on line 24
> ```

: Your Composer dependencies require a PHP version ">= 8.1.0". You are running 8.0.6.

**Comment by 1Q23LYC45** [comment]
![KSWeb-3.986](https://github.com/huankong233/94list-laravel/assets/143373643/8aaaa633-567a-454a-82c2-e2876e0740ca)

**Comment by 1Q23LYC45** [comment]
OK了，现在正常了。网上找了个最新版KSWeb3.988Pro，自己重新打包了一下，把TargetSDK改成28(安卓9)，然后去除了软件Nginx自带的错误伪静态规则，开启了AutoIndex功能。分享一下，链接：https://pan.95bl.com/s/64ZCd  
缺点就是这个版本不支持x86/amd64架构，安卓6.0以下也不能用最新版PHP8.2.6。我把3.986版本(支持所有架构)也放网盘里了。

**Comment by huankong233** [comment]
> OK了，现在正常了。网上找了个最新版KSWeb3.988Pro，自己重新打包了一下，把TargetSDK改成28(安卓9)，然后去除了软件Nginx自带的错误伪静态规则，开启了AutoIndex功能。分享一下，链接：https://pan.95bl.com/s/64ZCd 缺点就是这个版本不支持x86/amd64架构，安卓6.0以下也不能用最新版PHP8.2.6。我把3.986版本(支持所有架构)也放网盘里了。

x86环境一般也不会用这个哈哈哈，给你置顶一下

**Comment by huankong233** [comment]
现在最新版php版本需要≥8.2
