### ISSUE TITLE
询问下百度PCS接口内容

### ISSUE THREAD

**Issue by MoTeam-org** [huankong233/94list-laravel#62]
如题，我现在云端做好了，PanDownload的Lua请求，我在尝试通过d.pcs.baidu.com请求，我把数据发过去后，返回了以下内容
![image](https://github.com/huankong233/94list-laravel/assets/112475198/7aca774d-9f1f-4461-945e-9d43f00c7946)
我发现没办法完全对上请求downloadFiles的数据，你能否看看呢？

**Comment by huankong233** [comment]
https://github.com/huankong233/94list-laravel/blob/main/app/Http/Controllers/UserController.php#L304

下载部分代码

**Comment by MoTeam-org** [comment]
我看了发现有差距，这个代码是干啥的？

**Comment by huankong233** [comment]
> 我看了发现有差距，这个代码是干啥的？

下载文件，就是 `downloadFiles` 的实现部分

**Comment by MoTeam-org** [comment]
我还想询问下，怎么判断文件的类型，接口返回的数据哪个是判断其类型的？

**Comment by huankong233** [comment]
> 我还想询问下，怎么判断文件的类型，接口返回的数据哪个是判断其类型的？

https://blog.huankong.top/docs/94list-laravel/%E6%8E%A5%E5%8F%A3%E5%AE%9A%E4%B9%89/%E7%94%A8%E6%88%B7/#_2-%E8%8E%B7%E5%8F%96%E6%96%87%E4%BB%B6%E5%88%97%E8%A1%A8
