### ISSUE TITLE
指定用户解析是怎么出现的，以及如何关闭

### ISSUE THREAD

**Issue by candies404** [huankong233/94list-laravel#63]
![image](https://github.com/huankong233/94list-laravel/assets/154443166/8621dcdd-699c-470b-bf43-a692d339cc1e)

**Comment by huankong233** [comment]
> ![image](https://private-user-images.githubusercontent.com/154443166/323288003-8621dcdd-699c-470b-bf43-a692d339cc1e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMzNzEzMTgsIm5iZiI6MTcxMzM3MTAxOCwicGF0aCI6Ii8xNTQ0NDMxNjYvMzIzMjg4MDAzLTg2MjFkY2RkLTY5OWMtNDcwYi1iZjQzLWE2OTJkMzM5Y2MxZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxN1QxNjIzMzhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zOTM5M2Q3ZThiOTcwNDA0Y2IyNDZiZWMzYjc0ZWVlMzA1YjA1NzNlOTI3NTk4OGVlMTBkYTRhYTM2NDZlNWE3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.gCT0vHaGr4iVC0Z8aTBprFjoN5PbR-HQtb9j-3rPAOw)

指定用户解析暂时没有开启或关闭的开关

只有在登陆状态下才会有指定账户解析的输入框

并且未登录状态下如果传入了该字段会被拒绝请求

可以用于测试添加的账户是否可用

**Comment by candies404** [comment]
![image](https://github.com/huankong233/94list-laravel/assets/154443166/5f61483e-16b7-4ed8-90e0-b18d3244d6c4)
![image](https://github.com/huankong233/94list-laravel/assets/154443166/63908067-ef9b-4ba9-96ff-3e2d17c5de79)
![image](https://github.com/huankong233/94list-laravel/assets/154443166/b77e3d8b-43e8-4fd0-aacd-750b2c784512)

参数错误，怎么解决嘞，开不开无痕都会报参数错误

**Comment by huankong233** [comment]
> ![image](https://private-user-images.githubusercontent.com/154443166/323306835-5f61483e-16b7-4ed8-90e0-b18d3244d6c4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMzNzIyNjIsIm5iZiI6MTcxMzM3MTk2MiwicGF0aCI6Ii8xNTQ0NDMxNjYvMzIzMzA2ODM1LTVmNjE0ODNlLTE2YjctNGVkOC05MGUwLWIxOGQzMjQ0ZDZjNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxN1QxNjM5MjJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01MDNjNDc4MDkzNTc5MmMxZDAwNzlhN2I4ZTdjNmQ0YTczODM4ZjUzZmQ1NjFiM2E3MmNmZjAyZjViMzFkYmJjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.kL6o-JhDO6xVSBDJVIrQdmJ-C-c6dPLllneHDQ5RTiQ) ![image](https://private-user-images.githubusercontent.com/154443166/323307090-63908067-ef9b-4ba9-96ff-3e2d17c5de79.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMzNzIyNjIsIm5iZiI6MTcxMzM3MTk2MiwicGF0aCI6Ii8xNTQ0NDMxNjYvMzIzMzA3MDkwLTYzOTA4MDY3LWVmOWItNGJhOS05NmZmLTNlMmQxN2M1ZGU3OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxN1QxNjM5MjJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02Y2Q0NDU1MDViZDYwOWNhOTFhZTMxMzU1OTAyMjlhNjc5ODMxMDkzYTk4NWIxN2RhNTc4MDI3YWE0MDFjMmI0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.qGCjX51leznvysj1sHxGtr9-xute3hZQMS5L3WSKKis) ![image](https://private-user-images.githubusercontent.com/154443166/323307240-b77e3d8b-43e8-4fd0-aacd-750b2c784512.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMzNzIyNjIsIm5iZiI6MTcxMzM3MTk2MiwicGF0aCI6Ii8xNTQ0NDMxNjYvMzIzMzA3MjQwLWI3N2UzZDhiLTQzZTgtNGZkMC1hYWNkLTc1MGIyYzc4NDUxMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxN1QxNjM5MjJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04NmVjZWY4NzFiOGNiYTYwNWRhZGNlZWRhNTJjNTg0YzA3NjQxMzEzNTJiZDc1Y2RkODgzZTMwYzljMGE4ZTNhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.tO2P8XZJ9_qw24e0EPhpCzNyBCl6tLoEBhXd08PeD3A)
> 
> 参数错误，怎么解决嘞，开不开无痕都会报参数错误

可以回退一下版本，可能上次加的参数校验有点问题

**Comment by candies404** [comment]
好的

**Comment by huankong233** [comment]
> 好的

回退版本问题解决了吗，我这边测试了一下貌似没有什么问题啊

**Comment by huankong233** [comment]
> ![image](https://private-user-images.githubusercontent.com/154443166/323306835-5f61483e-16b7-4ed8-90e0-b18d3244d6c4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM0ODc0OTcsIm5iZiI6MTcxMzQ4NzE5NywicGF0aCI6Ii8xNTQ0NDMxNjYvMzIzMzA2ODM1LTVmNjE0ODNlLTE2YjctNGVkOC05MGUwLWIxOGQzMjQ0ZDZjNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxOVQwMDM5NTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iOGI1ZmE0ZTY0ZDVlMmM3OTMxMzA0OGFkNmUxMGE2Y2FiM2ZkOTM0NjU4YjExMjI3NWFhNzhmMjRlMDJhZWFhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Ze5QgS9xStIyg9sGKoxGS5UBPmMFniXDnepZkaeJMqA) ![image](https://private-user-images.githubusercontent.com/154443166/323307090-63908067-ef9b-4ba9-96ff-3e2d17c5de79.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM0ODc0OTcsIm5iZiI6MTcxMzQ4NzE5NywicGF0aCI6Ii8xNTQ0NDMxNjYvMzIzMzA3MDkwLTYzOTA4MDY3LWVmOWItNGJhOS05NmZmLTNlMmQxN2M1ZGU3OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxOVQwMDM5NTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mZWI1ODcxNDJkZmY2NDBkMzE0ZjM3MGNjNjczNDFkMzg2YjA1ZjA1MDRkZDA4MzFmYzU5YzE4NmVkZTZhNDgzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.iPncqwPXvIHy28lsZg69sFGVsR4DsPyx-2CH8Yc_dSI) ![image](https://private-user-images.githubusercontent.com/154443166/323307240-b77e3d8b-43e8-4fd0-aacd-750b2c784512.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM0ODc0OTcsIm5iZiI6MTcxMzQ4NzE5NywicGF0aCI6Ii8xNTQ0NDMxNjYvMzIzMzA3MjQwLWI3N2UzZDhiLTQzZTgtNGZkMC1hYWNkLTc1MGIyYzc4NDUxMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxOVQwMDM5NTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02ZmVhNzg2MGRhYWY2Njg1NDc1MDg0ZWJjNjdjMzBjNmEyYWI1NzdjYmM4OGI2NDIwZmM1OGQ1YWRkZDE2YjVmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.UtEK5mVJwDJraRClKqEiNSwiWbykx7HJ9syGQFbdwIY)
> 
> 参数错误，怎么解决嘞，开不开无痕都会报参数错误

![image](https://github.com/huankong233/94list-laravel/assets/49610758/eae2eb11-bdab-4c1c-9755-0864c474a67d)

好像不是最新版啊，应该还是版本的问题

**Comment by candies404** [comment]
> > 好的
> 
> 回退版本问题解决了吗，我这边测试了一下貌似没有什么问题啊

0.2.4 我用着没问题

**Comment by huankong233** [comment]
> > > 好的
> > 
> > 
> > 回退版本问题解决了吗，我这边测试了一下貌似没有什么问题啊
> 
> 0.2.4 我用着没问题

0.2.5有问题对吧，我再仔细检查一下

**Comment by huankong233** [comment]
![image](https://github.com/huankong233/94list-laravel/assets/49610758/83b4ec8c-80c2-44c1-ae82-b793aab36747)

应该是这个返回的参数错误，那个问一下是一次性请求了多个文件遇到了这个问题吧，我觉得可能是被风控一次下载过多文件了？但是我加了延迟了已经

**Comment by huankong233** [comment]
> 就1~5的左右，我昨天换0.2.4的时候当时就可以用了 顺便问下 未使用是被风控了吧 ![image](https://private-user-images.githubusercontent.com/154443166/323803893-dd1f9a24-0c71-41ba-b0ca-ee30191ef0c2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM0OTA5MzAsIm5iZiI6MTcxMzQ5MDYzMCwicGF0aCI6Ii8xNTQ0NDMxNjYvMzIzODAzODkzLWRkMWY5YTI0LTBjNzEtNDFiYS1iMGNhLWVlMzAxOTFlZjBjMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxOVQwMTM3MTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mZjM2NDIzMzFmYmNiMjJkM2Y4ZThlZmZhMWMxYjU5ZTFjZmNkZGFhYzdmNTk3YWYyZmI4NmU5YmE5ZGFkNTMzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.rIzbPX6kLhhlVbjkvbWqD9scwC5UKnXEW9fSQn4s7mE)

没有，被风控了也会有提醒的
![image](https://github.com/huankong233/94list-laravel/assets/49610758/58411b98-6e07-4b20-90d4-49f092c55501)

**Comment by huankong233** [comment]
> 就1~5个左右文件，我昨天换0.2.4的时候当时就可以用了 顺便问下 未使用是被风控了吧 ![image](https://private-user-images.githubusercontent.com/154443166/323803893-dd1f9a24-0c71-41ba-b0ca-ee30191ef0c2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM0OTA5NDQsIm5iZiI6MTcxMzQ5MDY0NCwicGF0aCI6Ii8xNTQ0NDMxNjYvMzIzODAzODkzLWRkMWY5YTI0LTBjNzEtNDFiYS1iMGNhLWVlMzAxOTFlZjBjMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxOVQwMTM3MjRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05MDVjNWMyYWY0YTlmMmFlYmEzODVmOWUwZGQ5MjhmNjBkMzc2MjVhMDA1NzE5NWUxYzVhNDFlZDhjNzQ1Y2MwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.X_wHTLvFHhKQY117ikxYfqiFNUVWxnlQLrWwGXV1utI)

这么奇怪嘛，我再研究一下，能给个联系方式嘛

**Comment by huankong233** [comment]
已修复
