### ISSUE TITLE
代理账号失效或者IP被封禁,code:8001

### ISSUE THREAD

**Issue by yzq313** [huankong233/94list-laravel#65]
这是什么问题？
![image](https://github.com/huankong233/94list-laravel/assets/67686611/f0751420-759e-40c5-9f21-7a77b255c7d1)

**Comment by huankong233** [comment]
> 这是什么问题？ ![image](https://private-user-images.githubusercontent.com/67686611/324332694-f0751420-759e-40c5-9f21-7a77b255c7d1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM3NjI0NTAsIm5iZiI6MTcxMzc2MjE1MCwicGF0aCI6Ii82NzY4NjYxMS8zMjQzMzI2OTQtZjA3NTE0MjAtNzU5ZS00MGM1LTlmMjEtN2E3N2IyNTVjN2QxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIyVDA1MDIzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZiNzFlNGY2MTc1YzU0NTAzY2MxMjg4MTRmNGQwY2ZkOThhNjI3NjhmMTE4ODQ4NDg0ODVjOWZiZmExN2YyZjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Pfb35CHi-K_zIg0d5pRPF2w25y423DjVKUfQEA8qzAg)

就提示的问题，换个ip试试看呢，这个错误码我是抄的 baiduwp-php 的

**Comment by yzq313** [comment]
好像还是不行

**Comment by huankong233** [comment]
> 好像还是不行

换号呢

**Comment by yzq313** [comment]
可以了
