### ISSUE TITLE
SVIP账号状态判断有误

### ISSUE THREAD

**Issue by MoTeam-org** [huankong233/94list-laravel#67]
出现账号是否正常的判断问题，我这边刚才发现，VIP账号实际没被限制，然而却出现了禁言问题，这个问题待优化！！！

**Comment by huankong233** [comment]
> 出现账号是否正常的判断问题，我这边刚才发现，VIP账号实际没被限制，然而却出现了禁言问题，这个问题待优化！！！

嗯，发现问题了，在重构新的，耐心等待，晚点丢个补丁

**Comment by huankong233** [comment]
> 出现账号是否正常的判断问题，我这边刚才发现，VIP账号实际没被限制，然而却出现了禁言问题，这个问题待优化！！！

有对应的错误码吗

**Comment by huankong233** [comment]
应该是在获取 `dlink` 的地方出问题了

因为我之前也是用 `SVIP` 的号获取的，这是一处不恰当的地方，打算在 `2.0` 里改了

你遇到的情况应该是 被限制获取 `dlink` 了，但是没有限制获取真实的下载链接

**Comment by MoTeam-org** [comment]
> 应该是在获取 `dlink` 的地方出问题了
> 
> 因为我之前也是用 `SVIP` 的号获取的，这是一处不恰当的地方，打算在 `2.0` 里改了
> 
> 你遇到的情况应该是 被限制获取 `dlink` 了，但是没有限制获取真实的下载链接

嗯嗯，我暂时把账号禁用功能给注释掉了，暂时没问题

**Comment by MoTeam-org** [comment]
有补丁的话，发个链接我上传上去

**Comment by huankong233** [comment]
> 有补丁的话，发个链接我上传上去

https://github.com/huankong233/94list-laravel/tree/dev-old

好像知道是什么毛病了，前面分析的不是很正确，我同步一下main分支，你再尝试一下

**Comment by huankong233** [comment]
> > 有补丁的话，发个链接我上传上去
> 
> https://github.com/huankong233/94list-laravel/tree/dev-old
> 
> 好像知道是什么毛病了，前面分析的不是很正确，我同步一下main分支，你再尝试一下

已同步

**Comment by MoTeam-org** [comment]
> > 有补丁的话，发个链接我上传上去
> 
> https://github.com/huankong233/94list-laravel/tree/dev-old
> 
> 好像知道是什么毛病了，前面分析的不是很正确，我同步一下main分支，你再尝试一下

你更新了什么？我直接复制过去

**Comment by huankong233** [comment]
> > > 有补丁的话，发个链接我上传上去
> > 
> > 
> > https://github.com/huankong233/94list-laravel/tree/dev-old
> > 好像知道是什么毛病了，前面分析的不是很正确，我同步一下main分支，你再尝试一下
> 
> 你更新了什么？我直接复制过去

[见此处 ](https://github.com/huankong233/94list-laravel/commit/8e6ced515a19cf1f556eb824b2b5b18cd9b540e6#diff-8e91484f56a38d906339650a2e3af6dbda84b6a43e6d889b792bd55b53a54e76)

**Comment by huankong233** [comment]
错误码应该是 9015 或 -20(clienttype=0时)
对应的原因是撞验证码了

**Comment by huankong233** [comment]
![213e1dd3ffb007cf8a7f219ea6a5673b](https://github.com/huankong233/94list-laravel/assets/49610758/44de8f10-c12a-47ce-a67d-1f691e952f6e)

靠，但是我现在没有会撞验证码的号了，试了几个都没验证码

**Comment by MoTeam-org** [comment]
> ![213e1dd3ffb007cf8a7f219ea6a5673b](https://private-user-images.githubusercontent.com/49610758/327915028-44de8f10-c12a-47ce-a67d-1f691e952f6e.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ3OTM1MDMsIm5iZiI6MTcxNDc5MzIwMywicGF0aCI6Ii80OTYxMDc1OC8zMjc5MTUwMjgtNDRkZThmMTAtYzEyYS00N2NlLWE2N2QtMWY2OTFlOTUyZjZlLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA0VDAzMjY0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJmOTA3OTcxZmVmODBkYWZhNjlhNjlmOWEwNDRhODI2ODIyMDZkNDI4NWMxMDdlY2JiMzJkYzBkYzdmYTdmMGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nWuNUoG7QUlONHZzcsRrtL9MjYdk613ejtM_hHh9sNU) [ ![213e1dd3ffb007cf8a7f219ea6a5673b](https://private-user-images.githubusercontent.com/49610758/327915028-44de8f10-c12a-47ce-a67d-1f691e952f6e.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ3OTM1MDMsIm5iZiI6MTcxNDc5MzIwMywicGF0aCI6Ii80OTYxMDc1OC8zMjc5MTUwMjgtNDRkZThmMTAtYzEyYS00N2NlLWE2N2QtMWY2OTFlOTUyZjZlLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA0VDAzMjY0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJmOTA3OTcxZmVmODBkYWZhNjlhNjlmOWEwNDRhODI2ODIyMDZkNDI4NWMxMDdlY2JiMzJkYzBkYzdmYTdmMGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nWuNUoG7QUlONHZzcsRrtL9MjYdk613ejtM_hHh9sNU) ](https://private-user-images.githubusercontent.com/49610758/327915028-44de8f10-c12a-47ce-a67d-1f691e952f6e.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ3OTM1MDMsIm5iZiI6MTcxNDc5MzIwMywicGF0aCI6Ii80OTYxMDc1OC8zMjc5MTUwMjgtNDRkZThmMTAtYzEyYS00N2NlLWE2N2QtMWY2OTFlOTUyZjZlLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA0VDAzMjY0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJmOTA3OTcxZmVmODBkYWZhNjlhNjlmOWEwNDRhODI2ODIyMDZkNDI4NWMxMDdlY2JiMzJkYzBkYzdmYTdmMGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nWuNUoG7QUlONHZzcsRrtL9MjYdk613ejtM_hHh9sNU) [ ](https://private-user-images.githubusercontent.com/49610758/327915028-44de8f10-c12a-47ce-a67d-1f691e952f6e.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ3OTM1MDMsIm5iZiI6MTcxNDc5MzIwMywicGF0aCI6Ii80OTYxMDc1OC8zMjc5MTUwMjgtNDRkZThmMTAtYzEyYS00N2NlLWE2N2QtMWY2OTFlOTUyZjZlLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA0VDAzMjY0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJmOTA3OTcxZmVmODBkYWZhNjlhNjlmOWEwNDRhODI2ODIyMDZkNDI4NWMxMDdlY2JiMzJkYzBkYzdmYTdmMGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nWuNUoG7QUlONHZzcsRrtL9MjYdk613ejtM_hHh9sNU)
> 
> 靠，但是我现在没有会撞验证码的号了，试了几个都没验证码

额，我是直接把检测逻辑K了...

**Comment by MoTeam-org** [comment]
> 错误码应该是 9015 或 -20(clienttype=0时) 对应的原因是撞验证码了

我现在听原来F4Pan得运营者说，百度有个现在都没有人用的接口，在客户端内，反向推出来的，我在尝试找出来，这样子号就不容易G了，走Share接口很容易GG

**Comment by huankong233** [comment]
> > 错误码应该是 9015 或 -20(clienttype=0时) 对应的原因是撞验证码了
> 
> 我现在听原来F4Pan得运营者说，百度有个现在都没有人用的接口，在客户端内，反向推出来的，我在尝试找出来，这样子号就不容易G了，走Share接口很容易GG

web端也有，要保存到svip账户里，但是这样要做的逻辑判断会有点多

**Comment by MoTeam-org** [comment]
> > > 错误码应该是 9015 或 -20(clienttype=0时) 对应的原因是撞验证码了
> > 
> > 
> > 我现在听原来F4Pan得运营者说，百度有个现在都没有人用的接口，在客户端内，反向推出来的，我在尝试找出来，这样子号就不容易G了，走Share接口很容易GG
> 
> web端也有，要保存到svip账户里，但是这样要做的逻辑判断会有点多

嗯，是的，我在尝试改造后端了，参考了你的后端改的，在尝试了

**Comment by huankong233** [comment]
> > > > 错误码应该是 9015 或 -20(clienttype=0时) 对应的原因是撞验证码了
> > > 
> > > 
> > > 我现在听原来F4Pan得运营者说，百度有个现在都没有人用的接口，在客户端内，反向推出来的，我在尝试找出来，这样子号就不容易G了，走Share接口很容易GG
> > 
> > 
> > web端也有，要保存到svip账户里，但是这样要做的逻辑判断会有点多
> 
> 嗯，是的，我在尝试改造后端了，参考了你的后端改的，在尝试了

保存的话，又要考虑如果空间不够怎么办

**Comment by MoTeam-org** [comment]
> > > > > 错误码应该是 9015 或 -20(clienttype=0时) 对应的原因是撞验证码了
> > > > 
> > > > 
> > > > 我现在听原来F4Pan得运营者说，百度有个现在都没有人用的接口，在客户端内，反向推出来的，我在尝试找出来，这样子号就不容易G了，走Share接口很容易GG
> > > 
> > > 
> > > web端也有，要保存到svip账户里，但是这样要做的逻辑判断会有点多
> > 
> > 
> > 嗯，是的，我在尝试改造后端了，参考了你的后端改的，在尝试了
> 
> 保存的话，又要考虑如果空间不够怎么办

嗯嗯，我去尝试了

**Comment by huankong233** [comment]
> > > > > > 错误码应该是 9015 或 -20(clienttype=0时) 对应的原因是撞验证码了
> > > > > 
> > > > > 
> > > > > 我现在听原来F4Pan得运营者说，百度有个现在都没有人用的接口，在客户端内，反向推出来的，我在尝试找出来，这样子号就不容易G了，走Share接口很容易GG
> > > > 
> > > > 
> > > > web端也有，要保存到svip账户里，但是这样要做的逻辑判断会有点多
> > > 
> > > 
> > > 嗯，是的，我在尝试改造后端了，参考了你的后端改的，在尝试了
> > 
> > 
> > 保存的话，又要考虑如果空间不够怎么办
> 
> 嗯嗯，我去尝试了

是一种思路，但是会大量操作文件，1.0里先把share方式写好了，再尝试一下这个

**Comment by huankong233** [comment]
计划功能已全部完成, 可以尝试安装体验了。

**Comment by MoTeam-org** [comment]
> 计划功能已全部完成, 可以尝试安装体验了。

好的，我试试，还有，直接源代码安装框架会报错不知道为什么

**Comment by huankong233** [comment]
> > 计划功能已全部完成, 可以尝试安装体验了。
> 
> 好的，我试试，还有，直接源代码安装框架会报错不知道为什么

需要安装依赖

**Comment by MoTeam-org** [comment]
> > > > 计划功能已全部完成, 可以尝试安装体验了。
> > > 
> > > 
> > > 好的，我试试，还有，直接源代码安装框架会报错不知道为什么
> > 
> > 
> > 需要安装依赖
> 
> 然后复制.env.example到.env打开页面

真就离谱了，请求downloadFiles接口报错500，一开Debug就把服务器卡死了

**Comment by MoTeam-org** [comment]
看那报错就是 发件邮箱 被限制 然后呢 请求downloadFiles就500，建议改下这个逻辑，刚把邮件通知关了

**Comment by huankong233** [comment]
> 看那报错就是 发件邮箱 被限制 然后呢 请求downloadFiles就500，建议改下这个逻辑，刚把邮件通知关了

哦，我想起来了，我忘记catch了，应该加个catch

**Comment by MoTeam-org** [comment]
> > 看那报错就是 发件邮箱 被限制 然后呢 请求downloadFiles就500，建议改下这个逻辑，刚把邮件通知关了
> 
> 哦，我想起来了，我忘记catch了，应该加个catch

额....很搞人心态的！

**Comment by huankong233** [comment]
> > > 看那报错就是 发件邮箱 被限制 然后呢 请求downloadFiles就500，建议改下这个逻辑，刚把邮件通知关了
> > 
> > 
> > 哦，我想起来了，我忘记catch了，应该加个catch
> 
> 额....很搞人心态的！

可是默认没开发送邮件啊🥺，我push一下，改好了

**Comment by huankong233** [comment]
> > > > 看那报错就是 发件邮箱 被限制 然后呢 请求downloadFiles就500，建议改下这个逻辑，刚把邮件通知关了
> > > 
> > > 
> > > 哦，我想起来了，我忘记catch了，应该加个catch
> > 
> > 
> > 额....很搞人心态的！
> 
> 可是默认没开发送邮件啊🥺，我push一下，改好了

要开的话有个发送测试邮件，可以先试一下能不能发

**Comment by huankong233** [comment]
> > > 看那报错就是 发件邮箱 被限制 然后呢 请求downloadFiles就500，建议改下这个逻辑，刚把邮件通知关了
> > 
> > 
> > 哦，我想起来了，我忘记catch了，应该加个catch
> 
> 额....很搞人心态的！

pull一下

**Comment by MoTeam-org** [comment]
> > > > > 看那报错就是 发件邮箱 被限制 然后呢 请求downloadFiles就500，建议改下这个逻辑，刚把邮件通知关了
> > > > 
> > > > 
> > > > 哦，我想起来了，我忘记catch了，应该加个catch
> > > 
> > > 
> > > 额....很搞人心态的！
> > 
> > 
> > 可是默认没开发送邮件啊🥺，我push一下，改好了
> 
> 要开的话有个发送测试邮件，可以先试一下能不能发

我测试过，可能是被限制频率了，今天发了几十个，然后被限制后downloadFiles就出问题了，甚至getConfig都Server Error了，就只有getFileList和getSign没问题...

**Comment by MoTeam-org** [comment]
我现在直接改了.env了，没有前端，前端一直进不去...现在好了

**Comment by huankong233** [comment]
> > > > > > 看那报错就是 发件邮箱 被限制 然后呢 请求downloadFiles就500，建议改下这个逻辑，刚把邮件通知关了
> > > > > 
> > > > > 
> > > > > 哦，我想起来了，我忘记catch了，应该加个catch
> > > > 
> > > > 
> > > > 额....很搞人心态的！
> > > 
> > > 
> > > 可是默认没开发送邮件啊🥺，我push一下，改好了
> > 
> > 
> > 要开的话有个发送测试邮件，可以先试一下能不能发
> 
> 我测试过，可能是被限制频率了，今天发了几十个，然后被限制后downloadFiles就出问题了，甚至getConfig都Server Error了，就只有getFileList和getSign没问题...

新的没有getSign啊，你是不是克隆错分支了，是dev分支哦

**Comment by MoTeam-org** [comment]
> > > > > > > 看那报错就是 发件邮箱 被限制 然后呢 请求downloadFiles就500，建议改下这个逻辑，刚把邮件通知关了
> > > > > > 
> > > > > > 
> > > > > > 哦，我想起来了，我忘记catch了，应该加个catch
> > > > > 
> > > > > 
> > > > > 额....很搞人心态的！
> > > > 
> > > > 
> > > > 可是默认没开发送邮件啊🥺，我push一下，改好了
> > > 
> > > 
> > > 要开的话有个发送测试邮件，可以先试一下能不能发
> > 
> > 
> > 我测试过，可能是被限制频率了，今天发了几十个，然后被限制后downloadFiles就出问题了，甚至getConfig都Server Error了，就只有getFileList和getSign没问题...
> 
> 新的没有getSign啊，你是不是克隆错分支了，是dev分支哦

上次你说的我克隆的，新的还没有，待会试试

**Comment by huankong233** [comment]
> > > > > > > > 看那报错就是 发件邮箱 被限制 然后呢 请求downloadFiles就500，建议改下这个逻辑，刚把邮件通知关了
> > > > > > > 
> > > > > > > 
> > > > > > > 哦，我想起来了，我忘记catch了，应该加个catch
> > > > > > 
> > > > > > 
> > > > > > 额....很搞人心态的！
> > > > > 
> > > > > 
> > > > > 可是默认没开发送邮件啊🥺，我push一下，改好了
> > > > 
> > > > 
> > > > 要开的话有个发送测试邮件，可以先试一下能不能发
> > > 
> > > 
> > > 我测试过，可能是被限制频率了，今天发了几十个，然后被限制后downloadFiles就出问题了，甚至getConfig都Server Error了，就只有getFileList和getSign没问题...
> > 
> > 
> > 新的没有getSign啊，你是不是克隆错分支了，是dev分支哦
> 
> 上次你说的我克隆的，新的还没有，待会试试

老的停止维护了，直接用新的，新的优化了解析的问题，还有用户组，邀请码

**Comment by MoTeam-org** [comment]
额，新版没getSign了 ？ 整合到哪个里面了 ？

**Comment by huankong233** [comment]
> 额，新版没getSign了 ？ 整合到哪个里面了 ？

在调用 downloadFiles 的时候，内部获取sign和timestamp，

或许不应该这样操作😕，有待商榷，本来是有的，但是我当时觉得没必要，就去掉了，接口是留了，没公开出来

我现在想到一个更好的方案，明天改一下

**Comment by huankong233** [comment]
https://github.com/huankong233/94list-laravel/blob/dev/app/Http/Controllers/ParseController.php

解析的逻辑部分都在这里了

**Comment by MoTeam-org** [comment]
> > 额，新版没getSign了 ？ 整合到哪个里面了 ？
> 
> 在调用 downloadFiles 的时候，内部获取sign和timestamp，
> 
> 或许不应该这样操作😕，有待商榷，本来是有的，但是我当时觉得没必要，就去掉了，接口是留了，没公开出来
> 
> 我现在想到一个更好的方案，明天改一下

嗯嗯，好的

**Comment by huankong233** [comment]
> > > 额，新版没getSign了 ？ 整合到哪个里面了 ？
> > 
> > 
> > 在调用 downloadFiles 的时候，内部获取sign和timestamp，
> > 或许不应该这样操作😕，有待商榷，本来是有的，但是我当时觉得没必要，就去掉了，接口是留了，没公开出来
> > 我现在想到一个更好的方案，明天改一下
> 
> 嗯嗯，好的

已修改
