### ISSUE TITLE
程序更新问题

### ISSUE THREAD

**Issue by yzq313** [huankong233/94list-laravel#71]
更新的时候不能直接用最新版本覆盖更新吗？我从2.6更新2.7直接覆盖然后修改数据库信息前台报错

**Comment by yzq313** [comment]
![image](https://github.com/huankong233/94list-laravel/assets/67686611/61f2bb60-6378-422a-999d-68646b83bb11)
删除安装锁后用原数据库重新安装也报错

**Comment by yzq313** [comment]
> ![image](https://private-user-images.githubusercontent.com/67686611/327516004-61f2bb60-6378-422a-999d-68646b83bb11.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ2Njk3MTMsIm5iZiI6MTcxNDY2OTQxMywicGF0aCI6Ii82NzY4NjYxMS8zMjc1MTYwMDQtNjFmMmJiNjAtNjM3OC00MjJhLTk5OWQtNjg2NDZiODNiYjExLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTAyVDE3MDMzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVlZDQ0ZDhkMzczNzI0ZDBkNjVkOTBkYTgyNjY5ZTBiMTgyMmM1MDVhMDZmMWVhNTZhYzNjZjY5ZjVkMDViZDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5rqB1TBN5rH1cC8wuFi8cSztbtLB9jVUKk5OoWjrHPw) 删除安装锁后用原数据库重新安装也报错

只能把原数据库内容删除重新安装

**Comment by huankong233** [comment]
> 更新的时候不能直接用最新版本覆盖更新吗？我从2.6更新2.7直接覆盖然后修改数据库信息前台报错

翻了一下commit记录我好像没有动和数据库字段有关的内容，可以看一下报什么错吗

**Comment by huankong233** [comment]
> 忘了截图了，好像是显示sqllite错误，地址是database/database，我用的mysql

我看看代码，可能哪里判断有毛病

**Comment by huankong233** [comment]
安装方式是什么

**Comment by yzq313** [comment]
宝塔安装


> 安装方式是什么

**Comment by huankong233** [comment]
> 忘了截图了，好像是显示sqllite错误，地址是database/database，我用的mysql

哦，我知道了，你直接把解压的 .env 文件替换掉了，所以导致了报错，这个小细节我在 1.0 重构里也解决了，敬请期待吧

**Comment by yzq313** [comment]
🆗

**Comment by huankong233** [comment]
![image](https://github.com/huankong233/94list-laravel/assets/49610758/e9217aae-9117-4dfe-87b8-235fc1234731)

默认配置的数据库使用的是sqlite，顺便提一嘴，1.0默认直接使用sqlite，还没写mysql，个人觉得sqlite管理起来问题也不是很大哈哈，晚点写完再写兼容好了

**Comment by yzq313** [comment]
sqllite个人感觉不如MySQL好用，主要是宝塔用习惯了

获取Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
