### ISSUE TITLE
账号获取dlink失败

### ISSUE THREAD

**Issue by yzq313** [huankong233/94list-laravel#72]
![image](https://github.com/huankong233/94list-laravel/assets/67686611/f5d1992d-0723-4971-84c6-43ce14a62d7f)
最新027版本报错

**Comment by huankong233** [comment]
> ![image](https://private-user-images.githubusercontent.com/67686611/327517682-f5d1992d-0723-4971-84c6-43ce14a62d7f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ2NzAwMTgsIm5iZiI6MTcxNDY2OTcxOCwicGF0aCI6Ii82NzY4NjYxMS8zMjc1MTc2ODItZjVkMTk5MmQtMDcyMy00OTcxLTg0YzYtNDNjZTE0YTYyZDdmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTAyVDE3MDgzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ3NDY1ZjM3MTY3NWVmMGNjZjFkZjliNzI3Yjk5YjliN2M3YmYzN2Q3MzNiOTFiMGU0YWU4MzQxNjA1ZTk3Y2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ptLuHwNP8ejrkbYyO6AoYCTeLO5bRDDmjHovqlOCGkU) 最新027版本报错

出现这个错误可以试试看多试几次，我这里测试有的时候也会这样，如果连续几次获得这个报错，可能是黑了

**Comment by yzq313** [comment]
换了个号好了，应该是之前的号黑了

**Comment by huankong233** [comment]
> 换了个号好了，应该是之前的号黑了

旧版本使用会员账号去解析dlink，会有些浪费，黑号原因可以看这个 https://github.com/yuantuo666/baiduwp-php/issues/364

**Comment by huankong233** [comment]
问题同 https://github.com/huankong233/94list-laravel/issues/67 等待 1.0 重构优化此问题

**Comment by huankong233** [comment]
> 换了个号好了，应该是之前的号黑了

应该不是黑号了，是遇上验证码了

**Comment by huankong233** [comment]
> > 换了个号好了，应该是之前的号黑了
> 
> 旧版本使用会员账号去解析dlink，会有些浪费，黑号原因可以看这个 [yuantuo666/baiduwp-php#364](https://github.com/yuantuo666/baiduwp-php/issues/364)

这个理解有误
