### ISSUE TITLE
Cookie怎么填的？

### ISSUE THREAD

**Issue by johIanse** [huankong233/94list-laravel#73]
抓了好几次，填了很多，都是提示这个

call to a member function getbody() on null

**Comment by huankong233** [comment]
> 抓了好几次，填了很多，都是提示这个
> 
> call to a member function getbody() on null

打开debug模式，然后在network里提供一下完整的报错信息，提供一下你的cookie

**Comment by johIanse** [comment]
![Screenshot_2024-05-11-21-18-42-886_com android browser](https://github.com/huankong233/94list-laravel/assets/119712859/eeedac53-0af2-4867-b8db-58c2a61094e5)
BDUSS=ZjdHh0SnNHdEs5fmVIcDJnWjN5Mm5BazJMRXlYc0dTT1pNZjJmMDdBU1l-R1ptRVFBQUFBJCQAAAAAAQAAAAEAAACD4zCHvsHRvsS9AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAJhvP2aYbz9mbl; PANPSC=10221397658222268581%3AKkwrx6t0uHBWucd6sJi5q2999OpeuuTuZiRMv5L2UefnbjiB3MoyWGGKg9iSfbi3COfgdHnp14%2FTcWP0AT7c%2FuUsD4UH13lyg0mIZdLHpdSoi9xCZYEu8Sv6ybg1Y4OmX2XlUsKRi0awbthkud9n5a%2F6Ni0tMxHeQjQ1mFHTd8W55I5Cval%2Bkn1t8VXlRfZV; STOKEN=d36e8f2575b6ab300868e0464704792898f13bfc32f5989fb05de2ed97313224; ndut_fmt=CB3A575C78718F037FC35970BE28108E276416900D19F58664FBACC0656738AB; ND_FTID=SITuui3n1GEjVd2Npa6%2FiWCAZcnfayFpToU9LDgFMXmPew6JWoDZLOmPD3bYxeEQYLpKztESJJ24q%2B30TzwBCg%3D%3D

debug模式默认打开的吧

**Comment by huankong233** [comment]
> ![Screenshot_2024-05-11-21-18-42-886_com android browser](https://private-user-images.githubusercontent.com/119712859/329784284-eeedac53-0af2-4867-b8db-58c2a61094e5.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU0MzQwMDQsIm5iZiI6MTcxNTQzMzcwNCwicGF0aCI6Ii8xMTk3MTI4NTkvMzI5Nzg0Mjg0LWVlZWRhYzUzLTBhZjItNDg2Ny1iOGRiLTU4YzJhNjEwOTRlNS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxMVQxMzIxNDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02M2Q3MDkzYjA5OWNmNzlkN2QyM2Q4NDQ2MGU2YzgxZDk2YzIxNjc0MzJmNjQyNTVhZDUzZGQyYWMwYjk2M2QyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.FJfF7f5yZTzK8ouCyN1VSZku4cB7zeuYEsbFL3IusIQ) BDUSS=ZjdHh0SnNHdEs5fmVIcDJnWjN5Mm5BazJMRXlYc0dTT1pNZjJmMDdBU1l-R1ptRVFBQUFBJCQAAAAAAQAAAAEAAACD4zCHvsHRvsS9AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAJhvP2aYbz9mbl; PANPSC=10221397658222268581%3AKkwrx6t0uHBWucd6sJi5q2999OpeuuTuZiRMv5L2UefnbjiB3MoyWGGKg9iSfbi3COfgdHnp14%2FTcWP0AT7c%2FuUsD4UH13lyg0mIZdLHpdSoi9xCZYEu8Sv6ybg1Y4OmX2XlUsKRi0awbthkud9n5a%2F6Ni0tMxHeQjQ1mFHTd8W55I5Cval%2Bkn1t8VXlRfZV; STOKEN=d36e8f2575b6ab300868e0464704792898f13bfc32f5989fb05de2ed97313224; ndut_fmt=CB3A575C78718F037FC35970BE28108E276416900D19F58664FBACC0656738AB; ND_FTID=SITuui3n1GEjVd2Npa6%2FiWCAZcnfayFpToU9LDgFMXmPew6JWoDZLOmPD3bYxeEQYLpKztESJJ24q%2B30TzwBCg%3D%3D
> 
> debug模式默认打开的吧

对，f12开开看看具体堆栈

**Comment by huankong233** [comment]
有电脑吗

**Comment by johIanse** [comment]
无TG联系你 给网站你看看

**Comment by huankong233** [comment]
> 无TG联系你 给网站你看看

t.me/huan_kong

**Comment by huankong233** [comment]
> ![Screenshot_2024-05-11-21-18-42-886_com android browser](https://private-user-images.githubusercontent.com/119712859/329784284-eeedac53-0af2-4867-b8db-58c2a61094e5.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU0NDMyNjIsIm5iZiI6MTcxNTQ0Mjk2MiwicGF0aCI6Ii8xMTk3MTI4NTkvMzI5Nzg0Mjg0LWVlZWRhYzUzLTBhZjItNDg2Ny1iOGRiLTU4YzJhNjEwOTRlNS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxMVQxNTU2MDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wMzI4MDhjYWJmMjMyOTFlOGFlMDUwYWQzYTgzNjNlMDQyNjUxOTA1MzUwNTJmYzIyYzA2ZWY3ODg5MjEwNmU1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.0S6SC4M1ek-D5AK8COOu7uXSrtV2pLjUcSqc5uljtqg) BDUSS=ZjdHh0SnNHdEs5fmVIcDJnWjN5Mm5BazJMRXlYc0dTT1pNZjJmMDdBU1l-R1ptRVFBQUFBJCQAAAAAAQAAAAEAAACD4zCHvsHRvsS9AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAJhvP2aYbz9mbl; PANPSC=10221397658222268581%3AKkwrx6t0uHBWucd6sJi5q2999OpeuuTuZiRMv5L2UefnbjiB3MoyWGGKg9iSfbi3COfgdHnp14%2FTcWP0AT7c%2FuUsD4UH13lyg0mIZdLHpdSoi9xCZYEu8Sv6ybg1Y4OmX2XlUsKRi0awbthkud9n5a%2F6Ni0tMxHeQjQ1mFHTd8W55I5Cval%2Bkn1t8VXlRfZV; STOKEN=d36e8f2575b6ab300868e0464704792898f13bfc32f5989fb05de2ed97313224; ndut_fmt=CB3A575C78718F037FC35970BE28108E276416900D19F58664FBACC0656738AB; ND_FTID=SITuui3n1GEjVd2Npa6%2FiWCAZcnfayFpToU9LDgFMXmPew6JWoDZLOmPD3bYxeEQYLpKztESJJ24q%2B30TzwBCg%3D%3D
> 
> debug模式默认打开的吧

![image](https://github.com/huankong233/94list-laravel/assets/49610758/e20724dd-06df-43f2-b1ba-f17b08649d76)

使用dev分支版本可以正常添加，老版本停止维护，只接受外部贡献
