### ISSUE TITLE
支持选中多个文件后，批量解析下载吗？

### ISSUE THREAD

**Issue by Gloryandel** [huankong233/94list-laravel#75]
支持选中多个文件后，批量解析下载吗？貌似只能解析并发送双击一个文件的文件。UI 中有功能选项但是是禁用状态

**Comment by huankong233** [comment]
> 支持选中多个文件后，批量解析下载吗？貌似只能解析并发送双击一个文件的文件。UI 中有功能选项但是是禁用状态

支持

**Comment by huankong233** [comment]
> 支持选中多个文件后，批量解析下载吗？貌似只能解析并发送双击一个文件的文件。UI 中有功能选项但是是禁用状态

但是请更新一下，晚上推送了一个补丁解决按钮无法使用的问题，但是推荐去dev分支用新版本，老版本应该不会维护了

**Comment by Gloryandel** [comment]
> > 支持选中多个文件后，批量解析下载吗？貌似只能解析并发送双击一个文件的文件。UI 中有功能选项但是是禁用状态
> 
> 但是请更新一下，晚上推送了一个补丁解决按钮无法使用的问题，但是推荐去dev分支用新版本，老版本应该不会维护了

大佬，Dev 版怎么部署啊，没找到 Docker 镜像😳

**Comment by huankong233** [comment]
> > > 支持选中多个文件后，批量解析下载吗？貌似只能解析并发送双击一个文件的文件。UI 中有功能选项但是是禁用状态
> > 
> > 
> > 但是请更新一下，晚上推送了一个补丁解决按钮无法使用的问题，但是推荐去dev分支用新版本，老版本应该不会维护了
> 
> 大佬，Dev 版怎么部署啊，没找到 Docker 镜像😳

docker镜像还没做，因为还没稳定下来，经常会更新，打包比较麻烦，可以用bt那种类型部署，会用的话用php的docker镜像挂载上去也可以用
