### ISSUE TITLE
配置完 打开报错了

### ISSUE THREAD

**Issue by zz6853** [huankong233/94list-laravel#8]
![看图王截图20230925221526](https://github.com/huankong233/94list-laravel/assets/58268737/c48aa15d-8af2-48e5-99ab-e3d7fe0a0ac7)
这是什么原因呀 哥哥

**Comment by zz6853** [comment]
完蛋了  涉及盲区了  这要怎么操作

**Comment by huankong233** [comment]
> 完蛋了 涉及盲区了 这要怎么操作

https://github.com/huankong233/94list-laravel#%E5%AE%89%E8%A3%85%E6%96%B9%E6%B3%95

**Comment by zz6853** [comment]
我就是根据[独角发卡]的安装步骤的

**Comment by zz6853** [comment]
php版本选多少合适

**Comment by huankong233** [comment]
> 我就是根据[独角发卡]的安装步骤的

https://github.com/assimon/dujiaoka/wiki/linux_install#%E5%AE%89%E8%A3%85composer%E4%BE%9D%E8%B5%96

**Comment by huankong233** [comment]
> php版本选多少合适

≥8.1

**Comment by 1Q23LYC45** [comment]
把下面网盘里所有文件解压到源码根目录试试，仅限php8.1及以上
https://pan.95bl.com/s/gEmT9

**Comment by 1Q23LYC45** [comment]
有root权限的，可以直接用Docker装
