### ISSUE TITLE
系统bug

### ISSUE THREAD

**Issue by yzq313** [huankong233/94list-laravel#80]
![image](https://github.com/huankong233/94list-laravel/assets/67686611/b0df42fe-7f95-4d22-826f-14e20161d848)

- 最新版本102仍出现输入中不能回车换行的bug，只有在后面有内容的时候才可以换行

- 且出现公告内容在.env中重复保存

![image](https://github.com/huankong233/94list-laravel/assets/67686611/62e9fb21-a238-46ce-9ad0-dfdb50625e82)

**Comment by huankong233** [comment]
![image](https://github.com/huankong233/94list-laravel/assets/49610758/02f9c9cb-e511-4998-b8da-cb5844a8b80d)

截图一下此接口，我看一下数据

**Comment by huankong233** [comment]
> ![image](https://private-user-images.githubusercontent.com/49610758/329857332-02f9c9cb-e511-4998-b8da-cb5844a8b80d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU1MjQ4MDQsIm5iZiI6MTcxNTUyNDUwNCwicGF0aCI6Ii80OTYxMDc1OC8zMjk4NTczMzItMDJmOWM5Y2ItZTUxMS00OTk4LWI4ZGEtY2I1ODQ0YThiODBkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTEyVDE0MzUwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY3NTBhOGYxMWQwYjk2YTJjMmNiZTAzNWZjZjg1MWE0MjBmZDM3YWE3ZDliMTJiNjE5N2NkOTM2YzMwOWU4ODUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.OkTm-liomtbDU9V460zYZ-BMgAiyGaV7MpLtpKO4tVU)
> 
> 截图一下此接口，我看一下数据

换行我在后端都替换成了[NextLine]来存储的🤔

**Comment by huankong233** [comment]
![image](https://github.com/huankong233/94list-laravel/assets/49610758/a502eab9-5749-497a-9d27-2f9479c89f0c)

检查一下这个37行

**Comment by huankong233** [comment]
不能换行应该是你的前端代码没有更新，强制刷新一下

**Comment by yzq313** [comment]
![image](https://github.com/huankong233/94list-laravel/assets/67686611/bbd3b92c-954a-4f9d-b78b-d2e102d3f1fe)

**Comment by huankong233** [comment]
> ![image](https://private-user-images.githubusercontent.com/67686611/329857943-bbd3b92c-954a-4f9d-b78b-d2e102d3f1fe.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU1MjUzNjksIm5iZiI6MTcxNTUyNTA2OSwicGF0aCI6Ii82NzY4NjYxMS8zMjk4NTc5NDMtYmJkM2I5MmMtOTU0YS00ZjlkLWI3OGItZDJlMTAyZDNmMWZlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTEyVDE0NDQyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM2NjYxNDBjYzRlYjc1M2RlMjhkZjhlNzRhNWQ1YWM3MmMwYjE2MmZiYTAwMzhjNmNhZTQ0ZDZiMjQyYzk3ZWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.oqCwxamqARNut_ki0_1NasbzlY9JPuutLHbAXVEOMlU)

检查一下上面那个第37行代码

**Comment by yzq313** [comment]
![image](https://github.com/huankong233/94list-laravel/assets/67686611/38a15835-1e85-43f7-acc1-2d6cab8c8755)

**Comment by huankong233** [comment]
> ![image](https://private-user-images.githubusercontent.com/67686611/329858096-38a15835-1e85-43f7-acc1-2d6cab8c8755.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU1MjU0ODEsIm5iZiI6MTcxNTUyNTE4MSwicGF0aCI6Ii82NzY4NjYxMS8zMjk4NTgwOTYtMzhhMTU4MzUtMWU4NS00M2Y3LWFjYzEtMmQ2Y2FiOGM4NzU1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTEyVDE0NDYyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg2ODE4MmQzMjQ3ODBjYzJmZTMyNDRlNWNlMDU2M2I4MDBiNDg1NzA3ZTA5MDMxY2MxMWM3ZmEwYmMwODJkZjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.kU19uQJfpDMeDgMcS8DvHyAj4UWIJWPizkvMbAKuSRA)

这还是老的代码啊，没有更新呀，前端也还是老的代码

**Comment by yzq313** [comment]
怪了，我直接下载的dev包啊

**Comment by huankong233** [comment]
> 怪了，我直接下载的dev包啊

去下一个新的，直接替换试试

**Comment by yzq313** [comment]
![image](https://github.com/huankong233/94list-laravel/assets/67686611/e02deb54-14a5-4c4c-bd82-b19780c6e382)
替换之后好像数据库有问题了

**Comment by huankong233** [comment]
> ![image](https://private-user-images.githubusercontent.com/67686611/329858817-e02deb54-14a5-4c4c-bd82-b19780c6e382.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU1MjYxMjYsIm5iZiI6MTcxNTUyNTgyNiwicGF0aCI6Ii82NzY4NjYxMS8zMjk4NTg4MTctZTAyZGViNTQtMTRhNS00YzRjLWJkODItYjE5NzgwYzZlMzgyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTEyVDE0NTcwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRlY2JkZjRiNzU4N2ZhMmZmZmZmZDZlNTJlY2ZjYTI1NmQyNjY2OWI2ZTM1Y2U1NWNkNzNmMDZiMjJhOTg5MDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6Og17n-DutGwLZemzNuxRXiIvs-1qtphFkckfZPt6f8) 替换之后好像数据库有问题了

删掉重建试试呢，install.lock还有database/sqlite.database这两个文件

**Comment by yzq313** [comment]
换行问题还有cookie设置里也是一样

**Comment by huankong233** [comment]
> 换行问题还有cookie设置里也是一样

设置页面的两个版本是多少，都是1.0.2吗

**Comment by yzq313** [comment]
对
![image](https://github.com/huankong233/94list-laravel/assets/67686611/f6f5f06c-66a6-43f5-99cc-32c31f86acc7)

**Comment by huankong233** [comment]
> 对 ![image](https://private-user-images.githubusercontent.com/67686611/329859807-f6f5f06c-66a6-43f5-99cc-32c31f86acc7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU1MjY5MjAsIm5iZiI6MTcxNTUyNjYyMCwicGF0aCI6Ii82NzY4NjYxMS8zMjk4NTk4MDctZjZmNWYwNmMtNjZhNi00M2Y1LTk5Y2MtMzJjMzFmODZhY2M3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTEyVDE1MTAyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZlYWE4YTBkZmJlNDIzNDZkYzU0NjBiOWMwM2U4OThhMTc5ZDliNjdjOGIxMmJlYjAyYmY1ZjA1ZWRlMmJkNzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.B7Q_UQuJ6ePVewVyjkU5JxVE--cy8wiOgil59MoZNKI)

有联系方式吗

**Comment by yzq313** [comment]
tg：https://t.me/wocnz
