### ISSUE TITLE
docker 没有arm的 

### ISSUE THREAD

**Issue by srlihg66** [huankong233/94list-laravel#86]
你的docker文件里面引用了 nginx php也是自己创建的 没有相关构建信息  我的系统是arm的 可能不太适用 有相关信息用以构建吗 还是网上随便一个都行
我的linux 是rocky系统的 guzz那个http模块 我用不了  删除他说找不到 装上他500 研究几天了 用别的函数可以跑url  但是用他那个语法我单独去跑也不行 只会500 系统宽容也打开 找不出来什么问题 所以想搞到docker里面跑

**Comment by huankong233** [comment]
> 你的docker文件里面引用了 nginx php也是自己创建的 没有相关构建信息 我的系统是arm的 可能不太适用 有相关信息用以构建吗 还是网上随便一个都行 我的linux 是rocky系统的 guzz那个http模块 我用不了 删除他说找不到 装上他500 研究几天了 用别的函数可以跑url 但是用他那个语法我单独去跑也不行 只会500 系统宽容也打开 找不出来什么问题 所以想搞到docker里面跑

在此项目 https://github.com/TrafeX/docker-php-nginx 上添加了一些 Laravel 会用到的扩展

这是构建文件

```dockerfile
FROM trafex/php-nginx:latest

USER root
RUN apk add --no-cache php83-common php83-ldap php83-mysqli php83-odbc php83-xsl php83-apcu php83-gmp php83-pgsql php83-bz2 php83-imap php83-cgi php83-cli php83-tokenizer php83-pdo php83-zip php83-iconv php83-fileinfo php83-json php83-xmlwriter php83-simplexml php83-pdo_mysql php83-pdo_sqlite php83-pecl-redis
USER nobody
```

**Comment by srlihg66** [comment]
好的谢谢

**Comment by huankong233** [comment]
https://github.com/huankong233/php-nginx

安心用 🧐
