### ISSUE TITLE
一些错误提交

### ISSUE THREAD

**Issue by onlys86** [huankong233/94list-laravel#87]
1. 添加账号时可添加相同的账号
2. 超级会员cookie失效时禁用原因显示为账号限速
3. 会员类型为普通用户的账户cookie失效时不会被禁用，且轮到该cookie失效普通账户时会导致正常可用的超级会员账户被禁用
4. 预览显示错误：鼠标放在下载链接上，显示错位了。在后台的记录管理里文件显示过多时同样会错位
![image](https://github.com/huankong233/94list-laravel/assets/169864571/0191a2e6-261b-41c4-8c11-8f3dcd7d9383)
5.缩短下载链接重新获取时间

**Comment by huankong233** [comment]
## 解决列表

- 1.因为获取不到百度账户id，所以使用用户名做判断，如果修改了用户名还是可以添加相同账户
- 2.已修正返回和提示的信息
- 3.可能需要测试一下(未修复)
- 4.可能需要提交给 `element-plus` 团队修复
- 5.已调整为2小时
