### ISSUE TITLE
请问可以直接环境变量配置数据库之类的跳过安装吗

### ISSUE THREAD

**Issue by cooliceycold** [huankong233/94list-laravel#9]

**Comment by huankong233** [comment]
可以，但是不推荐

手动按照.env.example来配置好.env文件，然后在根目录创建install.lock文件即可跳过安装

**Comment by huankong233** [comment]
> _No description provided._

你的数据库账户密码泄露了，把仓库改为私有，而且镜像不要上传到dockerhub

**Comment by cooliceycold** [comment]
我想在zeabur 或者render上部署不知道文件目录  直接修改.env 创建install.lock 就可以吗 还是要直接放在 app或者public目录下

**Comment by huankong233** [comment]
> 我想在zeabur 或者render上部署不知道文件目录 直接修改.env 创建install.lock 就可以吗 还是要直接放在 app或者public目录下

直接在项目根目录创建即可

**Comment by cooliceycold** [comment]
十分感谢

**Comment by huankong233** [comment]
> 我想在zeabur 或者render上部署不知道文件目录 直接修改.env 创建install.lock 就可以吗 还是要直接放在 app或者public目录下

你可以直接在我原有的镜像的基础上添加文件即可，但是你如果把.env打包在镜像里，那样后台的修改就是一次性的了
