### ISSUE TITLE
更新账号出错

### ISSUE THREAD

**Issue by yzq313** [huankong233/94list-laravel#93]
![image](https://github.com/huankong233/94list-laravel/assets/67686611/c4e28e4e-6c26-46a5-8d9b-bab64788baf3)

**Comment by huankong233** [comment]
> ![image](https://private-user-images.githubusercontent.com/67686611/332092096-c4e28e4e-6c26-46a5-8d9b-bab64788baf3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYzMzg2MzgsIm5iZiI6MTcxNjMzODMzOCwicGF0aCI6Ii82NzY4NjYxMS8zMzIwOTIwOTYtYzRlMjhlNGUtNmMyNi00NmE1LThkOWItYmFiNjQ3ODhiYWYzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIyVDAwMzg1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk2ZDNlNDE3NWUyYjcxZjA0Y2Y0YjkwZTEyNjk5OGEzNGU1NmRkZGE4ZTYxYjJjM2JmODkzOWMyZmMxOTQ4NDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nc1SB58CaLtxpK1qUEUsmna7MRjhd_2cuKFOQeQJxVA)

复现步骤

**Comment by yzq313** [comment]
更新至最新版本显示cookie过期，可能是号的问题
