### ISSUE TITLE
文件解析

### ISSUE THREAD

**Issue by yzq313** [huankong233/94list-laravel#97]
同一个文件短时间内多次解析只算一次的大小还是解析一次另算一次？

**Comment by huankong233** [comment]
> 同一个文件短时间内多次解析只算一次的大小还是解析一次另算一次？

解析一次算一次

**Comment by huankong233** [comment]
> 同一个文件短时间内多次解析只算一次的大小还是解析一次另算一次？

因为实现的逻辑是这样的，缓存的是 `dlink` ，如果解析到同一个文件，还是需要用 `dlink` 去获取一次 `reallink`，获取成功就会记录一次记录
